### ISSUE TITLE
SimpleHistory Error

### ISSUE THREAD

**Issue by AziRizvi** [Eisa01/mpv-scripts#102]
If you have multiple items in your playlist and you try to cycle through the entire playlist too quickly, and then try to open SimpleHistory it just stops working and throws out multiple errors in the console, if you try to use any of the Keybinds like the alphabet h key or Shift+H to open SimpleHistory, it either says that no such Keybind exists or doesn't do anything.

Two Screenshots of the error: 

1- https://i.imgur.com/vPOq7eh.png
2- https://i.imgur.com/uJVbPD5.png

I reproduced this error on my main MPV build with other scripts as well as on one of Shinchiro's latest releases without any other scripts just to make sure that any other scripts I had wasn't causing it to break and the behaviour was the same, I also tried this on MPV.net and the behaviour there was the same too.

**Comment by Eisa01** [comment]
Please provide version number you are attempting with (script and mpv).
Also, just out of curiosity, can you test if the issue occurrs if you have `--keep-open=` set to `yes` or `always` in your mpv.conf file.

**Comment by AziRizvi** [comment]
SimpleHistory Script -- Version: 1.1

I tried it on the following versions of MPV and MPV.net

1 - https://i.imgur.com/Kd9tGR3.png
2 - https://i.imgur.com/TXsydCN.png
3 - https://i.imgur.com/NwiaZrf.png

The behaviour was the same across all three versions and the behaviour was the same using the -keep-open set to yes or always, I also tried changing keep-open set to no and the behaviour was the same, I even removed it from the mpv.conf temporarily to see if it would change anything but the script behaviour remained the same, it's still throwing out the same errors.

**Comment by Eisa01** [comment]
Update to 1.1.6 because it contains many bug fixes and let me know if the issue is there.

**Comment by Eisa01** [comment]
Closed.
If issue exists in latest feel free to comment.

**Comment by AziRizvi** [comment]
> Closed. If issue exists in latest feel free to comment.

Apologies for the late reply I got a bit busy with some FFMPEG stuff.
I updated to script version 1.1.6 and since then it has stopped giving me the error, I tried my best to recreate it but it didn't happen, so I guess there was some bug in the old version.
