### ISSUE TITLE
SimpleHistory: Option for playing the file from the last saved position 'automatically'

### ISSUE THREAD

**Issue by asgharam** [Eisa01/mpv-scripts#106]
Hey.
First, I wanna say thank you for the effort. The scripts are super useful!
Second, As the title says I wanna know whether there is an option for the SimpleHistory script to open the file from the last saved position automatically. I know I can do that with Control+r when the video starts but I'm looking for a way to do that automatically as I am using mpv in a script. I checked the SimpleHistory.conf but the closest thing that I found out was the `auto_run_list_idle` but it works when no file is included to run with mpv.

**Comment by Eisa01** [comment]
Glad that you like it.
The option is there, just change resume_option to force 
`resume_option=force`
