### ISSUE TITLE
SmartSkip breaks sometimes.

### ISSUE THREAD

**Issue by AziRizvi** [Eisa01/mpv-scripts#109]
Sometimes when I'm using SmartSkip and I initiate a Skip to Silence using my keybind the audio keeps playing in the background and the track keeps playing normally and the skipping action does not work.

Video of the error.

https://github.com/Eisa01/mpv-scripts/assets/129892077/a2361f5e-d535-4b76-9cef-5cbfb1adec9b

As you can see and hear in the video above, I initiated Skip to Silence but it did not work so I clicked again to cancel it and then initiated it again, and kept doing this cycle until the 5th time I did it, it worked.

I can't be sure if this error is because of something in the SmartSkip's code or is caused by interference because of another lua script that I'm using so I thought I should share that I'm using a lua script called Speed Transition.

https://github.com/zenyd/mpv-scripts/blob/master/speed-transition.lua

This speed-transition script allows me to speed up the parts between the next subtitle if they're 5 seconds away from the previous subtitle.

I'm not sure if the Skipping Action breaks by itself or breaks because of Speed Transition script.
Just for more information, I'm sharing a list of all the scripts that I use.

![explorer_EnVCjcIy2P](https://github.com/Eisa01/mpv-scripts/assets/129892077/c7d15936-56b8-4b9b-ae64-cde1125e3de6)

**Comment by AziRizvi** [comment]
> Intersting.. Please test with only SmartSkip script, and let me know the results

Definitely, I will.
I will test it alone and with SmartSkip and let you know the results of what I find when I've tested it with enough files over the next few days.

**Comment by AziRizvi** [comment]
Currently I've tested with over 15 files and the issue only happens when Speed Transition is enabled and it doesn't happen otherwise.

I will do some more testing and report back.

**Comment by Eisa01** [comment]
Closed, looks like a conflict with the other script.
