### ISSUE TITLE
SimpleUndo: Deprecation warning for 'pause' and 'unpause' events

### ISSUE THREAD

**Issue by cherti** [Eisa01/mpv-scripts#12]
mpv from (at least) version 0.33 onwards reports

    [SimpleUndo_2_5_1] The 'pause' event is deprecated and will be removed.
    [SimpleUndo_2_5_1] The 'unpause' event is deprecated and will be removed.

Currently SimpleUndo still works without issues, but given the deprecation warning this might not be the case forever anymore.

**Comment by Eisa01** [comment]
New updates depreciating useful stuff, I hope that they provided an alternative. I'll be checking the api later. Thanks for reporting.

**Comment by Eisa01** [comment]
Closed for now, will attempt a workaround if possible after depreciation.

**Comment by Eisa01** [comment]
Fixed in PR#15
