### ISSUE TITLE
SimpleHistory get error in the lastest version of MPV

### ISSUE THREAD

**Issue by xiaozhubin** [Eisa01/mpv-scripts#121]
mpv has  remove `shared-script-properties` property, and use `user-data` instead. Could you fix the SimpleHistory script?
see https://github.com/mpv-player/mpv/commit/86b498ecc0e6276bb905df57f479d0506b45ba53

**Comment by AziRizvi** [comment]
> mpv has remove `shared-script-properties` property, and use `user-data` instead. Could you fix the SimpleHistory script? see [mpv-player/mpv@86b498e](https://github.com/mpv-player/mpv/commit/86b498ecc0e6276bb905df57f479d0506b45ba53)

What version of SimpleHistory are you using?
Use the Git Master version as that one already has the user-data fix.

Updated Script Link: https://raw.githubusercontent.com/Eisa01/mpv-scripts/master/scripts/SimpleHistory.lua
Updated Script-Opts (.Conf File) Link: https://raw.githubusercontent.com/Eisa01/mpv-scripts/master/script-opts/SimpleHistory.conf

Use them.

**Comment by xiaozhubin** [comment]
sorry, I didn't see the new script. It works well with the new scripts. thanks.
