### ISSUE TITLE
Notice: Wayland

### ISSUE THREAD

**Issue by solariz** [Eisa01/mpv-scripts#128]
Hey,

just a notice for anybody going to use the SmartCopyPaste.lua Scripts. On Wayland you cant go with xclip anymore. Short solution, install `wl-clipboard` and change the Script to use it instead of xclip:

	linux_copy = 'wl-copy',
	linux_paste = 'wl-paste',

Thats it, still beautifully working.

Cheers

**Comment by Eisa01** [comment]
Thanks for the notification, glad that the customisation came in handy. This will be useful for others as a reference. Closed.
