### ISSUE TITLE
LogManager: Greylist History.

### ISSUE THREAD

**Issue by AziRizvi** [Eisa01/mpv-scripts#130]
In LogManager we have whitelist and blacklist, everything is whitelisted by default and show up in the log and blacklisted paths don't show up at all, can we get some middle ground between the two?

What I mean is, can an option be added for GreyList history? Let's say that there are certain paths/directories from which I want the history to be recorded but I don't want it to show up in the main history log but in separate history log which can be toggled on/off which would be the Greylist History Log, I'm not talking about a separate category #126 because the history from the separate category would still show up in the main log, I'm talking about a separate log entirely.

I had two ideas for this, maybe a log containing the history from greylisted paths can be stored separately and it can be toggled on/off or the history from the greylisted paths can be appended to the main log when toggled on/off.
I'm more in favour of the first approach because it would help keep things separate but some people might appreciate both options.

Does this make sense? Or do you think it overlaps with #126?
I think it's a bit different because when cycling through all the categories as it will in #126 the category and the history would still show up in the main log when viewed, and what I'm talking about is kind of like.. hidden history for specific paths which can be toggled on/off.

**Comment by Eisa01** [comment]
This can be already covered by using categories, you can test it in SimpleBookmark until the migration. Basically, what needs to be done is change the default filter in the conf file to exclude a specific category. Then when adding a bookmark, you can assign it to that specific category. You can also choose to invoke the category only through specific key-bind.
If you want to also automate the process based on specific paths, then keywords filter can be utilized.

Try it out, if you have challenge in the conf, please refer to #66

**Comment by AziRizvi** [comment]
But what I'm talking about something that's a bit different isn't it?
What I'm talking about is a separate secondary log that just records/logs entries from certain paths, a log with its own categories and filters separate from the main log which can be toggled on/off when the main log is active.

For example when I play a file from e.g `K:\\LQ-Archives` it automatically logs that into the secondary log and not the main one.

I will try out what you're saying though, from what I understand, you're saying that removing a category from the filter would technically "hide" that category and then you could "call" that category with its keybind when the log is active.

Two things, one, wouldn't having a category mean that I would have to manually add every single logged item to that hidden category?

Also secondly what if one wants to see all the items from all the "hidden" categories together in a single log?

**Comment by AziRizvi** [comment]
I tried out what you said and I've discovered a small problem.

If you add something to a group/category and that category/group was hidden because its removed from the filters, when the log is open and you press the keybind to activate that group/category even once, after closing the log, that group/category will start showing up in the filters again despite having hidden it by removing it from the filters in the conf file.

Two, I added the second log item to the hidden category but when the log is opened, that entry still shows up.

![mpv_y7l6cGYVTw](https://github.com/Eisa01/mpv-scripts/assets/129892077/62bae034-b031-484b-aa00-e49ac624c2ef)

But I guess the workaround for this second thing would be to change the default logmanager view from all to all-groups-keybinds and because a group is hidden, an entry from that wouldn't show.

**Comment by Eisa01** [comment]
> Two things, one, wouldn't having a category mean that I would have to manually add every single logged item to that hidden category? Whereas in the first approach that I suggested, if there was a separate log that just logs entries from certain directories, it would do that automatically.

For your first problem statement, it can be automated by utilizing "keywords" filter.  
```
#--["string","..."]. Create a filter out of your desired 'keywords', e.g.: youtube.com will filter out the videos from youtube. You can also insert a portion of filename or title, or extension or a full path / portion of a path. e.g.: ["youtube.com", "mp4", "naruto", "c:\\users\\eisa01\\desktop"]. To disable this filter keep it empty []
keywords_filter_list=[]
```
Basically, add the paths or whatever you want as part of your gray list here. No need to create a group, just ensure that you replace `all` in the script-opts to be `all%-%keywords%` This will automate the process.

As for your second problem statement, I didnt understand it, will appreciate detailed clarification.
 > If you add something to a group/category and that category/group was hidden because its removed from the filters, when the log is open and you press the keybind to activate that group/category even once, after closing the log, that group/category will start showing up in the filters again despite having hidden it by removing it from the filters in the conf file.

**Comment by AziRizvi** [comment]
I'm really sorry I haven't checked back in on this, I've been really sick, I'll check things out soon when I'm feeling better.

**Comment by AziRizvi** [comment]
I had a chance to test things out today and I'm afraid that testing things on the bookmark logmanager is proving to be a little troublesome and is confusing.. I'm going to close this one for now and wait for the logmanager migration to be done, when the migration is done I will test this out again and if there's a need, I will reopen a new issue.

Thank you for your patience and again I'm sorry I couldn't test it out and reply earlier.
I was really sick.
