### ISSUE TITLE
SmartCopyPaste: Wayland support

### ISSUE THREAD

**Issue by jnothan** [Eisa01/mpv-scripts#131]
Would it be possible to add simple Wayland support for Linux? I've done this by editing the optional configuration file with

```
linux_copy=wl-copy
linux_paste=wl-paste
```

As far as I know, most Wayland compositors integrate wl-clipboard, so it should be a pretty universal solution to use. The main script could perform a check whether the user is using X11 or Wayland with the `XDG_SESSION_TYPE` environment variable.

**Comment by Eisa01** [comment]
I believe having the optional configuration is enough. 
Automatic detection based on Linux flavours seems a bit too much?
