### ISSUE TITLE
SimpleHistory stopped working

### ISSUE THREAD

**Issue by plissken1138** [Eisa01/mpv-scripts#133]
SimpleHistory worked well but at some point last month or so it stopped logging titles. 

I tried deleting the log content to see if it will create a new one and it doesn't.
I tried deleting the log file to see if it will create a new one and it doesn't.

Always using the latest shinchiro mpv build., 1.1.6 lua and 1.1.5. conf.
Win10 Edu 22H2

**Comment by Eisa01** [comment]
Please share your mpv logs after opening a video, so that i can see what's happening

**Comment by plissken1138** [comment]
https://pastebin.com/WvpqQP2E

to my layman eye, seems there's some issue with 'history_blacklist' 

`[   1.315][f][SimpleHistory] Lua error: C:/Program Files/mpv/mpv/scripts/SimpleHistory.lua:1961: attempt to index field 'history_blacklist' (a nil value)`

**Comment by Eisa01** [comment]
Can you revert to default config for the script and check?

**Comment by plissken1138** [comment]
Ah, the culprit is identified! 
One of  blacklisted entries had \ instead \\ in folder structure...
I was almost positive that it was working after I added that entry, but I guess it's by bad :)

**Comment by Eisa01** [comment]
Glad that it is sorted :)
