### ISSUE TITLE
simlehistory autoload in history postion

### ISSUE THREAD

**Issue by sqq135** [Eisa01/mpv-scripts#139]
Because I was watching drama series that was a bit brain-burning, and I watched it repeatedly to look for clues. But when I came back, it started from the beginning, and I had to re-submit and start pulling up the timeline. 

#--Keybind that will be used to immediately load and resume last item when no video is playing. If video is playing it will resume to the last found position
history_resume_keybind=["ctrl+r", "ctrl+R"]

I don't want to push this keybind everytime, how should I make this the default setting?

**Comment by Eisa01** [comment]
```
#--none: for disabled. notification: a message to resume the previous reached time will be triggered. force: to forcefully resume last playback based on threshold
resume_option=notification
```
Change to `resume_option=force`
