### ISSUE TITLE
Difficulties in configuring the script

### ISSUE THREAD

**Issue by Niotferdi** [Eisa01/mpv-scripts#14]
Without a configuration file, it is very difficult to customize the behavior of the script (for example, change the path to save the history file) if you have no knowledge of programming. Please make a config file.

**Comment by Eisa01** [comment]
Are you referring to SmartHistory or SmartCopyPaste-II?
Also what other configurations you see are needed other than changing the path of history file?

**Comment by Niotferdi** [comment]
I mean Smart History.
I would like to see in the configuration file the same, for example, a template for building a line - select data that will be stored in lines, their sequence, and constant characters (for example, separating characters that will be the same for all lines).

There is only one configurable parameter at the beginning of the script. But there are more things in the script that could work differently.

**Comment by Eisa01** [comment]
Can you give me exactly what other configuration parameters are needed, also let me know what you arr trying achieve

**Comment by Eisa01** [comment]
Awaiting update.
If no update is provided, will mark as not needed and will be closed within 30 days.

**Comment by Niotferdi** [comment]
In addition to the wishes already mentioned, I would like to be able to change the month record from alphabetic to numeric (for example, January as "01", not as "jan").

**Comment by Eisa01** [comment]
Providing different logging options might make reading easier for some users, however these changes will affect how the values are used to make the resume option and loading last video works.
To program them again, I will need to program some functions that I don't think are worth it right now.

Might be a good addition for the future.
Closed.

**Comment by Eisa01** [comment]
New version released with a configuration file has tons of configuration options.
