### ISSUE TITLE
SmartCopyPaste II on macos and youtube

### ISSUE THREAD

**Issue by Bellavene** [Eisa01/mpv-scripts#140]
Works only if mpv had been started from the shell. If you open it like a normal GUI app, the script adds the link to the playlist, but nothing starts playing.

**Comment by Eisa01** [comment]
I cannot seem to replicate the issue, please try it with only SmartCopyPaste. Temporarily remove all other scripts as there could be an interference.

**Comment by Bellavene** [comment]
Same. Maybe it is related to specific mpv version.
