### ISSUE TITLE
Error on the command line

### ISSUE THREAD

**Issue by zhouxinghong** [Eisa01/mpv-scripts#146]
Error on the command line
![image](https://github.com/Eisa01/mpv-scripts/assets/54253524/30b8e27c-3fed-4f5f-9284-dd27e1afb3ac)
Windows 10 19044
mpv 0.38

**Comment by Eisa01** [comment]
It looks like your windows instance is missing Get-FileHash a powershell module. It is be default pre-installed. 
Please try to install it and let me know if it solves it for you

**Comment by zhouxinghong** [comment]
This itself is integrated into Windows 10 by default, how else do I install it?

**Comment by Eisa01** [comment]
You can try updating your powershell to the latest, and check the version of powershell also:
https://github.com/PowerShell/PowerShell/releases

**Comment by zhouxinghong** [comment]
![image](https://github.com/Eisa01/mpv-scripts/assets/54253524/075ca4a0-705f-4ac1-9573-355f674d0b0c)

**Comment by Eisa01** [comment]
> Also, you can try to open powershell from your device, then run
    Get-FileHash
   Just to make sure if you have Get-FileHash or not.

...

**Comment by Eisa01** [comment]
Anyway, I'll be closing this as it doesn't seem to be an issue with the script directly.
It could be resolved if you research onto why Get-FileHash is not working on your system.

**Comment by zhouxinghong** [comment]
Works well with older versions of powershell 5.x

**Comment by zhouxinghong** [comment]
![image](https://github.com/Eisa01/mpv-scripts/assets/54253524/9bef8a0f-d094-4531-af8e-f60dc0058549)
![image](https://github.com/Eisa01/mpv-scripts/assets/54253524/d528c771-b7f0-44f0-bf21-0dac21d04d12)
You can try updating your powershell to the latest, and check the version of powershell also:
https://github.com/PowerShell/PowerShell/releases

**Comment by zhouxinghong** [comment]
mpv https://www.youtube.com/watch?v=NcRifDitRnU
