### ISSUE TITLE
[input] No key binding found for key 'H'. SimpleHistory

### ISSUE THREAD

**Issue by Znote** [Eisa01/mpv-scripts#150]
As per install instructions, I have placed the SimpleHistory.lua file in `/home/znote/.config/mpv/scripts` and `/home/znote/.config/mpv/script-opts`. When I run a video file in MPV and press h (default keybinding to open history) I get this message:
```
[input] No key binding found for key 'H'.
```

I have a feeling Im missing a presumed obvious install instruction "how to activate default key bindings". Or "how to autoload scripts", but alas. Perhaps someone can enlighten me?

```
mpv --version
mpv v0.38.0-dirty Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jun  8 2024 07:59:48
libplacebo version: v6.338.2
FFmpeg version: 7.0.1
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100

neofetch --stdout
znote@Froeya 
------------ 
OS: Ubuntu 24.04 LTS x86_64 
Host: MINIPC PN52 
Kernel: 6.8.0-35-generic 
Uptime: 1 hour, 43 mins 
Packages: 2138 (dpkg), 7 (flatpak), 22 (snap) 
Shell: bash 5.2.21 
Resolution: 3840x2160 
DE: GNOME 46.0 
WM: Mutter 
WM Theme: Nordic-v40 
Theme: Yaru-red-dark [GTK2/3] 
Icons: Yaru-red [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 9 5900HX with Radeon Graphics (16) @ 4.680GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Memory: 8380MiB / 31487MiB

pwd && ls -R mpv/
/home/znote/.config
mpv/:
input.conf  mpv.conf  script-opts  scripts  script-settings

mpv/script-opts:
SimpleHistory.conf

mpv/scripts:
SimpleHistory.lua

mpv/script-settings:
SimpleHistory.conf

```

**Comment by Eisa01** [comment]
This looks like an issue that the script didn't load. There are multiple ways to getting started, please refer to the [mpv.io/manual](mpv.io/manual). And if after following the issue, then try seeking support from mpv main repository.

**Comment by Znote** [comment]
Just incase someone stumbles upon this in a search, the solution was to uninstall the snap package from software manager, and install mpv using the apt package repository. 
This also solves issues with mpv failing to read amdgpu ids and thus hardware acceleration as well. 
So the default snap package for mpv in Ubuntu 24.04 software center is total crap and should never be installed by anyone.
