### ISSUE TITLE
How to type search with simplehistory?

### ISSUE THREAD

**Issue by ShawnNogi** [Eisa01/mpv-scripts#155]
is there a hotkey or something? I see the video example that shows it but I can't seem to figure it out. It's not in the hotkeys section either?

![image](https://github.com/user-attachments/assets/2acf972c-13a9-4dfa-abf9-5fa4e2a6059a)

**Comment by Eisa01** [comment]
It is ctrl+f 
You can find it in LogManager keybinds section

**Comment by ShawnNogi** [comment]
@Eisa01 Thanks. do you have any idea why simplehistory sometimes has text overlay issues that look like this? Is it a resolution thing?
![image](https://github.com/user-attachments/assets/857fc2f6-b908-4b43-a0b0-6ce3f79a7174)
