### ISSUE TITLE
SmartHistory.lua

### ISSUE THREAD

**Issue by nobef** [Eisa01/mpv-scripts#169]
Sorry if I was wrong, I just downloaded and used this FILE a long time ago, now I can’t find the source, but I assume that now it’s SimpleHistory.lua?... 
![изображение](https://github.com/user-attachments/assets/cc55264a-ed80-4484-a23e-ece2f32a5633)

 So, is there a connection between these extensions and the history of mpv in the Roaming/mpv folder? So like "mpvHistory.log". 
![изображение](https://github.com/user-attachments/assets/d5db2539-db3e-4644-a68e-cf8cb240bf72)
 I can figure it out

**Comment by Eisa01** [comment]
Yes, the name has changed. Also opening previous history file is not supported. You need to rename / remove the old history file and it will create a new one that is supported.

**Comment by nobef** [comment]
@Eisa01 Thank you, everything worked. And not to open another question. I would like to disable the "incognito" function. Or be able to turn it off. I just don't use it and don't like a lot of hotkey bindings. For example, I disabled all built-in MPV hotkeys.
 Thank you.

**Comment by nobef** [comment]
And increase the font a little...
And even my font in the console is larger.
![image](https://github.com/user-attachments/assets/670c9bf0-d1bc-48d5-94da-b44fc1536450)
