### ISSUE TITLE
Lua script file name should not include version number

### ISSUE THREAD

**Issue by snowman** [Eisa01/mpv-scripts#17]
### description
When using `require("SCRIPT_NAME-VERSION")` to load Lua script, it'll first replace version
number with "directory separator"  in the modname, for example:

```lua
-- FILE: MPV_CONFIG_DIR/scripts/loader.lua
local smart_history = require "SmartHistory-1.7.1"
-- the same as
local smart_history = require "SmartHistory-1/7/1"
```

`require (modname)` document: https://www.lua.org/manual/5.1/manual.html#5.3

> The second searcher looks for a loader as a Lua library, using the
> path stored at package.path.
>
> A path is a sequence of templates separated by semicolons.
>
> For each template, the searcher will change each interrogation mark in
> the template by filename, which is the module name with each dot
> replaced by a "directory separator" (such as "/" in Unix); then it
> will try to open the resulting file name.
>
> So, for instance, if the Lua path is the string
>
>      "./?.lua;./?.lc;/usr/local/?/init.lua"
>
> the search for a Lua file for module foo will try to open the files
>
>   1. ./foo.lua
>   2. ./foo.lc
>   3. /usr/local/foo/init.lua
>
> in that order.

### What's expected?
Strip version number from the script file name, for example,
`SmartHistory-1.7.1.lua` should be renamed into `SmartHistory.lua`

**Comment by snowman** [comment]
Never mind it, when the loaded [seek-to.lua](https://github.com/occivink/mpv-scripts/#seek-tolua) script is *NOT* in `mpv_config_dir/scripts` directory, but load it using another lua loader script does *NOT* respond to the `input.conf` key bindings.

```conf
## FILE: input.conf
t script-message-to seek_to toggle-seeker
```

**Comment by snowman** [comment]
So I do not bother with the version number in your script file name, because the usage is not allowed currently.

**Comment by snowman** [comment]
Okay, This works for me.

```lua
-- FILE: input.conf
t script-message toggle-seeker
```

**Comment by snowman** [comment]
emmm, anyway, this is not the best practice. What if the script has `.conf` file?

so use this instead:
```lua
mp.command("load-script " .. "scripts/vendor/occivink/mpv-scripts/scripts/seek-to.lua")
-- you can even load javascript in the file loader.lua
```

and now both of the world are happy even the `.lua` script file name include version number :)

Thanks for the version number keep me practicing. ;)

**Comment by Eisa01** [comment]
I have no clue what you are trying to achieve and what you are doing

**Comment by snowman** [comment]
Use version number with dot(.) like `3.1` in [SimpleUndo-3.1.lua](https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SimpleUndo-3.1.lua) is not best practice, how about strip the version number `-3.1` off into `SimpleUndo.lua`

**Comment by Eisa01** [comment]
You can load the scripts, simply by placing them in the scripts directory. It will automatically use the script.
But I believe removing the version number is a better approach, I will be removing it in the future.
Feel free to remove it, it won't break anything.

**Comment by snowman** [comment]
#### Another example

If oneself wants to remap the keybinding,

```conf
## FILE: input.conf

## use "SmartHistory_1_7_1/resume" instead of "resume" to avoid conflict
x script-binding resume
x script-binding SmartHistory_1_7_1/resume

## same as above
x script-message                       resume
x script-message-to SmartHistory_1_7_1 resume
```

After upgrade `SmartHistory` from `1.7.1` into `1.7.2`, you have to change those `input.conf` accordingly. 

Thanks :heart:

**Comment by Eisa01** [comment]
Renamed version number from scripts
