### ISSUE TITLE
Default documentation of undo button is missing a step for MPV.net users

### ISSUE THREAD

**Issue by Starmann** [Eisa01/mpv-scripts#18]
MPV.net's default config includes a setting which clears input settings. This causes the undo button scripts to not work.

Fix:

Instruct MPV.net users to change `input-default-bindings = no` to `input-default-bindings = yes`

**Comment by Eisa01** [comment]
Can you tell me what is the conf file name and path is? So I add it to documentation

**Comment by Starmann** [comment]
It's %Appdata%/MPV.net/mpv.conf
