### ISSUE TITLE
Smartcopypaste with nircmd

### ISSUE THREAD

**Issue by Dimsok** [Eisa01/mpv-scripts#2]
Can you make modification of SmartCopyPaste-1.5 script to work with nircmd? I have Windows which doesn't have powershell, so it can't work with clipboard.

**Comment by Eisa01** [comment]
It will be good to experiment with this.
No ETA for now. Once I am done with other things, I will see if it feasible without any hiccups. 

Thanks for bringing this to my attention ^ ^

**Comment by Eisa01** [comment]
With the newer scripts and updates, getting this to work with nircmd is going to take a lot of time and will be challenging (i think).

Will close it until seeing that it is really needed or for when I have time to spare.

**Comment by Eisa01** [comment]
@Dimsok 
Updated the script multiple times, now it is multi-platform and has customizable settings.
It should be possible now to use nircmd or other programs.

There is now the option inside the script to write your own command for copy and paste 

You can to test it with the SmartCopyPaste-II 2.2 https://github.com/Eisa01/mpv-scripts/commit/130b1d1911600103143cea8fb8ffe584a39c49b7 or SmartCopyPaste 2.2 https://github.com/Eisa01/mpv-scripts/commit/ac4cbd0660cb0190cd215042143f10637f29313f 
https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SmartCopyPaste-II-2.2.lua
https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SmartCopyPaste-2.2.lua

Feel free to report if you encounter any issues.
