### ISSUE TITLE
SmartCopyPaste: Option to disable OSD?

### ISSUE THREAD

**Issue by uptightgnome** [Eisa01/mpv-scripts#21]
I recently installed [uosc](https://github.com/darsain/uosc) and found that when I pasted a link the default mpv OSD would turn back on. Nothing else causes this to occur so I assume that when SmartCopyPaste displays a message it forces the default OSD to turn back on. An option to disable OSD messages I believe would fix this.

**Comment by Eisa01** [comment]
I will verify and provide the option, seems like a good option to have anyways. I didn't think of it.
Thanks.
