### ISSUE TITLE
SmartCopyPaste Suggestion: Change format to "t=" for website links

### ISSUE THREAD

**Issue by Kerobyte** [Eisa01/mpv-scripts#22]
Both Youtube and Twitch use the "t=" parameter for timestamps
"?t=" at the start of a query or "&t=" otherwise
e.g.
https://www.youtube.com/watch?v=aFPJf-wKTd0&t=500s
https://www.twitch.tv/videos/1157674028?t=24156s

This would be more useful for copying these links to post to other places or people that don't use this script.

**Comment by Eisa01** [comment]
Earlier versions of the script had the `t=` parameter. Although, I changed it for some reason that I cannot recall.
However, I believe the best approach would be to handle each URL separately or maybe make the parameter user configurable. 


I will test it out when I am working on a new version. Thanks =)

**Comment by Eisa01** [comment]
New version released which has the option to specify different parameters for each website.
The default config includes youtube and twitch with their time parameters for copy.
