### ISSUE TITLE
Option to change log file location

### ISSUE THREAD

**Issue by dyphire** [Eisa01/mpv-scripts#23]
Portable mpv installation uses `portable_config` folder in the root of mpv installation for storing personal data.When using multiple mpv, scripts are required to adapt the portability configuration, such as using mpv and mpv.net at the same time.Thanks in advance.

**Comment by Eisa01** [comment]
If it's mpv and there is a scripts directory for it, it should work.
Do you mean you want to change the log file location for each script? So that MPV.net uses different log director and MPV uses a different ont?

**Comment by dyphire** [comment]
> If it's mpv and there is a scripts directory for it, it should work. Do you mean you want to change the log file location for each script? So that MPV.net uses different log director and MPV uses a different one?

I mean, log files can be saved in `portable_config` instead of appdata for Windows. In this way, there is no need to worry about conflicts between different MPV clients, because each MPV can have its own `portable_config`

**Comment by dyphire** [comment]
As for the specific implementation method, I think it isn't necessary to detect the path of appdata or home, but the upper folder where the script is located？

**Comment by Eisa01** [comment]
Ah so u mean the optional configuration parameters, not the logging.
This is possible to implement. However, it required additional mpv dependencies and files. I tried to keep it clean.

The portable configuration, is actually inside the script itself. You can open the script with a notepad and you will find a user customization section where u can change stuff. 

Is there any specific parameter you need to change but didn't find it?

**Comment by dyphire** [comment]
> Ah so u mean the optional configuration parameters, not the logging. This is possible to implement. However, it required additional mpv dependencies and files. I tried to keep it clean.
> 
> The portable configuration, is actually inside the script itself. You can open the script with a notepad and you will find a user customization section where u can change stuff.
> 
> Is there any specific parameter you need to change but didn't find it?

Sorry, I can't find the option to change the `*.log` path in the user customization section. Can you tell me how to do it? How to put `*.log`  in `portable_config` without absolute path?

**Comment by Eisa01** [comment]
I didn't make the option to change the log file location, ill make it next update. Which script are you using?

**Comment by dyphire** [comment]
> I didn't make the option to change the log file location, ill make it next update. Which script are you using?

I have use UndoRedo.lua,SmartHistory.lua and SmartCopyPaste-II.lua. Thank you for everything

**Comment by dyphire** [comment]
I found a solution for reference

change
```
local copyLog = (os.getenv('APPDATA') or os.getenv('HOME')..'/.config')..'/mpv/mpvClipboard.log'
local historyLog = (os.getenv('APPDATA') or os.getenv('HOME')..'/.config')..'/mpv/mpvHistory.log'
```
to
```
local copyLog = mp.find_config_file(".")..'mpvClipboard.log'
local historyLog = mp.find_config_file(".")..'mpvHistory.log'
```
This enables script log generation in  `portable_config`

**Comment by Eisa01** [comment]
Nice work, you digged inside the script and changed the path.
I'll keep this ticket open until I make it easy for others by putting the option above.

**Comment by dyphire** [comment]
I noticed that you updated these scripts recently. The new path is in mpv.exe works normally, but it is broken in libmpv, such as [mpv.net](https://github.com/stax76/mpv.net).

I tried the following modifications to fix, it work
Example: change
```
local copyLogPath = mp.find_config_file("."):match("@?(.*/)")
local copyLog = copyLogPath .. copyLogFile
```
to
```
local copyLogPath = mp.find_config_file(".")
local copyLog = copyLogPath ..'/'.. copyLogFile
```

**Comment by Eisa01** [comment]
Ah I see, appreciated I'll reflect in the new major version.
I am rewriting most of the scripts to include new useful enhancements and customizable options for almost everything.

**Comment by Eisa01** [comment]
3.0 version is released along with its config file. It covers these optional features and tons more.
You can confirm from your side so we close this
