### ISSUE TITLE
SmartHistory - Feature Request - Supporting Playlists

### ISSUE THREAD

**Issue by vivek201** [Eisa01/mpv-scripts#24]
Is it possible to support .m3u playlists using SmartHistory? If this could go to the last played file for the playlist, then I think it could work.

**Comment by Eisa01** [comment]
I think what you need is a way to bookmark the playlist file, then go to it easily.
Will an option to bookmark solve this issue?

**Comment by vivek201** [comment]
Yeah, if it will allow me to go back to that same file.

**Comment by Eisa01** [comment]
I will be releasing a new script powerful soon (couple of days) that makes bookmarking very simple. It will easily allow you to jump to any specific file.

I'll update you once it is out.
