### ISSUE TITLE
Can't paste YouTube links after updating to mpv 0.34.0-14-g662c793a55

### ISSUE THREAD

**Issue by ereinstein** [Eisa01/mpv-scripts#26]
Previously, I was able to copy YouTube links with SmartCopyPaste-II and just paste them into mpv. Ever since I upgraded to mpv 0.34.0-14-g662c793a55, I just get the message 

```
Failed to Paste
Pasted Unsupported Item:
```

and nothing else happens. I would like to provide more information but I don't really know what kind of information would be helpful and where to get it. I am on the Arch-based distro EndeavourOS, if that's important.

**Comment by Eisa01** [comment]
Thanks for letting me know.
No worries, I'll check it out soon

**Comment by Eisa01** [comment]
I have tested the stable mpv-0.34 and there does not seem to be an issue.
Which clipboard tool are you using to paste the links and what version?
And are you using the latest youtube-dl version ?

**Comment by ereinstein** [comment]
Unfortunately, I can't reproduce the issue any more. It started working again after I updated mpv. It could be that this was just a coincidence as well. Back then I was using (and I am still using) KDE Plasma's built-in clipboard manager and yt-dlp instead of youtube-dl.

**Comment by Eisa01** [comment]
Thanks for letting me know. Glad that updating mpv fixed it.
