### ISSUE TITLE
SimpleBookmark - Force SimpleBookmark to be left-aligned

### ISSUE THREAD

**Issue by Max-Enrik** [Eisa01/mpv-scripts#28]
I have set the OSD alignment to the right, but I need SimpleBookmark to be left-aligned.
Is it possible to do it?

Where have I tried to fix it? (Unfortunately, I didn't make it happen by myself.)

- SimpleBookmark.lua
- SimpleBookmark.conf

**Comment by Eisa01** [comment]
Wasn't aware there is right-alignment
if feasible, I'll test and add the option to force left alignment. Thanks for reporting

**Comment by Max-Enrik** [comment]
That will be great.

_Thank you for your scripts._

**Comment by Max-Enrik** [comment]
If there would be an option to adjust the `y-position`. That will be great too.

**Comment by Eisa01** [comment]
Sure, I'll add it

**Comment by Eisa01** [comment]
I added the option for alignment using numpad position.
Download the updated script and configuration file and the issue should be resolved.

### Additional Clarification:
In the configuration file, in List Design Settings section you will find `list_alignment=7`.
The default value is 7 which means top left according to numpad shape.
(e.g.: you can do 8 which means top middle, or 3 which means bottom right).
You can fiddle around and see the 9 options.


### Y-Position:
For the y-position it did not play nicely after adding the alignment option.

However, I have hack for you (if the 9 alignment options aren't enough). Go to  List Design Settings section:
Where it says `header_text=🔖 Bookmarks [%cursor/%total] %prefilter%filter%afterfilter%presearch%search%aftersearch`

Add before it `\\N` to increase the Y-Position. the more `\\N` you add the more it will increase.
e.g.:
`header_text=\\N\\N\\N\\N🔖 Bookmarks [%cursor/%total] %prefilter%filter%afterfilter%presearch%search%aftersearch`

Let me know if this solves both issues

**Comment by Max-Enrik** [comment]
Both work perfectly! Thank you very much.

**Comment by Eisa01** [comment]
Glad to hear it =)
