### ISSUE TITLE
SmartCopyPaste Option to disable copying time

### ISSUE THREAD

**Issue by MintMain21** [Eisa01/mpv-scripts#29]
I don't prioritize copying the time-stamp that much. Typically I only want to copy the link. I'd prefer to use the CTRL+C command to just copy the video link instead of CTRL+ALT+C.

There doesn't seem to be an option in the lua script to change these configurations. I could edit the imput.config file, but I'm uncertain how to appropriately do that without breaking something.

**Comment by Eisa01** [comment]
Already implemented this and tons of user customizable settings in the upcoming 3.0 version.
I'll be hopefully releasing it today or tomorrow

**Comment by Eisa01** [comment]
Alright, so you can now download SmartCopyPaste 3.0 and the configuration file for it in script-opts directory.

There are a lot of changes but for your case, you can now change the keybinds using the SmartCopyPaste.conf configuration file.

However, I suggest disabling or limiting copying time.
In SmartCopyPaste.conf line 38
change `copy_time_method=all` to `copy_time_method=none` for disabling

Or choose one of the available options explained in the settings to limit it, e.g.: `specifics` for only defined websites, `protocols` for all websites.

Let me know if this solves the issue

**Comment by MintMain21** [comment]
https://www.youtube.com/watch?v=nct3Bjj1iB8

Well, yeah, I guess it does.

But now I can't paste anything into the playlist. I get a message saying "pasting", but nothing happens after the fact. I have to drap/drop links/files instead of pasting them.

**Comment by Eisa01** [comment]
Ah no need to rename the ticket, opening new one for continuation is better.
What OS are you using?
also can you press <kbd>`</kbd> and copy the log after pasting. an error message should trigger

**Comment by MintMain21** [comment]
I'm using Linux Mint 20.2. When I view the log, it doesn't give me an error message, it just says "Pasting...."

**Comment by Eisa01** [comment]
I have updated the script, there was one missing line, also I added error messages in case it doesn't work.
Try and let me know

**Comment by MintMain21** [comment]
That fixes it! Thanks!
