### ISSUE TITLE
SmartCopyPaste 3.0: Option to Paste into Playlist by default?

### ISSUE THREAD

**Issue by MintMain21** [Eisa01/mpv-scripts#30]
Before I upgraded to SCP 3.0, anything I pasted into MPV would be pasted into the playlist by default, which I like. In SCP 3.0 however, the default behavior is to override the current video. I can customize behavior when a video is playing, and when using ctrl+alt+v, but if I have a video paused and use just ctrl+v, it will override my current playlist.

**Comment by Eisa01** [comment]
Hmm, I didn't quite fully get it. What is the behavior you are looking for that changed?
Also when a video is paused it should append to the playlist and not override it. I thought the same applies to older version?

**Comment by MintMain21** [comment]
Okay, on further testing, the bug only applies when I try to add another YouTube link, but the initial link hasn't fully loaded yet.

**Comment by Eisa01** [comment]
Can you compare with the version in the released section, tell me if the older version differed for you or had the same issue?

**Comment by MintMain21** [comment]
https://user-images.githubusercontent.com/91362684/147512276-5accde58-6a87-435a-a5c6-d70bbcc449bf.mp4

SmartCopyPaste Before and After. 2.5 vs 3.0.

**Comment by Eisa01** [comment]
Interesting, I'll attempt to replicate and hope to fix it by tomorrow

**Comment by MintMain21** [comment]
Alright, I decided instead of trying to change the function of default paste, I would just set the Paste-Specific behavior to "Playlist", and then swap the key-combination for normal paste and "Special Paste". Works fine for me. I'll leave this open in the event you want to change this behavior for the default release, otherwise feel free to close this issue.

**Comment by Eisa01** [comment]
Added a line that should fix the issue, test and let me know when you can =)

**Comment by MintMain21** [comment]
That fixed it. Thanks.

**Comment by Eisa01** [comment]
Glad that it is resolved, thanks for noticing issues with the 3.0 release.
Re-wrote most of the script in this version, hopefully no other bugs slipped .
