### ISSUE TITLE
SimpleHistory - text month to numeric month - conflict

### ISSUE THREAD

**Issue by Max-Enrik** [Eisa01/mpv-scripts#32]
The script doesn't read the log file anymore, and I think this issue comes from text month to numeric month.

```
log_path=C:\Users\Max\AppData\Roaming\mpv\_ZZZ
log_file=mpvHistory.log
```

**Comment by Eisa01** [comment]
Were you using SmartHistory before?
If so you will need to delete the log file so SimpleHistory creates a new one

**Comment by Max-Enrik** [comment]
Yes, I had to use it. Yep, that helped! Thank you!
