### ISSUE TITLE
Keybind overlap

### ISSUE THREAD

**Issue by Darkmaster006** [Eisa01/mpv-scripts#33]
Just wanted to let you know that the keybind 'r' and 'R' overlap with default mpv keyboards (for moving subtitles up and down). I changed these to 'y' and 'Y', but would recommend changing them so as not to have them overlapping.

**Comment by Eisa01** [comment]
Thanks for reporting, I think I will stick with [r, R] (until I find a better logical keybind) since I like it for recents. The option is there for any one who likes to change because of conflict
