### ISSUE TITLE
Total duration for video played in history + filtering - Feature Request 

### ISSUE THREAD

**Issue by Kayizoku** [Eisa01/mpv-scripts#34]
I thought this would be a cool idea, so I thought I'll let you know in hope of maybe seeing it implemented. What if the history section with all the episodes could show the total time spent on all things in total. That would mean all videos with the accurate time as shown by when you stopped noted by the clock icon and time. Another thing would be if you say wanted to know time spent on a certain playlist, say Breaking Bad season 1 you can just search that up, and the duration counted will adjust to those elements and ignore everything else that doesn't fit.  Time will only be counted if the video is playing from a continuation or if you decide to go back and play but not when you're paused. Hopefully, It makes any sense. I hope to hear from you soon. Thank you so much for all these awesome scripts :)

**Comment by Eisa01** [comment]
Glad that it is useful for you =)
So basically you want a total duration in the header for the displayed list, right?
E.g.
History [1/74] 🕜 72:52:01
History [1/13]  🕜 10:32:58 search="Breaking"

**Comment by Kayizoku** [comment]
> Glad that it is useful for you =) So basically you want a total duration in the header for the displayed list, right? E.g. History [1/74] 🕜 72:52:01 History [1/13] 🕜 10:32:58 search="Breaking"

haha, I should've explained it that earlier but that's exactly what I want. It would be a really cool feature IMO :)

**Comment by Eisa01** [comment]
Hmm, I think sticking with the hours format is the best approach.
Imagine searching or filtering content that have less than 1 day playback, the days format will not be appropriate I think

**Comment by Kayizoku** [comment]
Ah, I see what you mean.  You know best. I am just glad you are considering it. Thanks for that. I greatly appreciate it :)

**Comment by Eisa01** [comment]
I added the feature, and made it default for SimpleHistory. (I liked it as well)
Also, made the total list time automatically disappear if the search or filter doesn't have any time.

You can change how it looks like or even remove it through the custom options
in the conf file, the following are the related options:
`header_text=⌛ History [%cursor/%total] %prelistduration%listduration%afterlistduration%prefilter%filter%afterfilter%presearch%search%aftersearch`
The `%listduration`, found in the header_text is the one calling the feature.

The text behind it and after it can be customized using the below which is called by `%prelistduration`, `%afterlistduration`
`header_list_duration_pre_text=🕒 `

`header_list_duration_after_text=`

**Comment by Kayizoku** [comment]
Wow, this is exactly like I wanted and it's working perfectly. Thank you so much, that was also really fast :)

**Comment by Kayizoku** [comment]
I had a few questions and thought it would be more efficient to just open the same closed issue. I was wondering if it's possible to make the script only log history on a shortcut or toggle. So by pressing say x, I could turn it on or off. from logging, this should not affect the history key in any way. It would be really nifty if I wanted to ignore certain files from being tracked in history.

 Another thing is a weird bug I've noticed. If you delete every element in history that you either filtered out or searched for it will end up removing everything and lead to the history key not working anymore. Otherwise, it's working quite well. I just thought I should let you know about this bug. In addition, to my previous question :)

**Comment by Eisa01** [comment]
That is some serious bug you found, delete while filtered causes a very weird behavior. It is better to open a seperate issue and track it there.
Also, for the behavior you are requesting, why not use SimpleBookmark script? It has the same features of history, but it will only log when you press <kbd>ctrl+b</kbd>. Also, it is better to open separate issue for that, so I track things individually.
