### ISSUE TITLE
[BUG] Delete while filtered causes a very weird behavior

### ISSUE THREAD

**Issue by Kayizoku** [Eisa01/mpv-scripts#35]
Whenever I try to delete elements from the history by searching or filtering, the second I delete the last element on display the hotkey for opening history stops working. I have to reopen MPV to get it working. But the thing is when I do that all of the elements, even the ones I didn't want to clear get removed from history.

**Comment by Eisa01** [comment]
The bug should be fixed now in all scripts. Let me know if its fixed from your side so I push it as a new release.
Also, does SimpleBookmark solve the feature request you mentioned earlier?

**Comment by Kayizoku** [comment]
I've tested both simplebookmark and simplehistoryscript in many ways and none of them seem to produce those same bugs anymore. There's no doubt in my mind, they've been fixed once and for all. Thank you again for the swift and solid service. Your script are really improving my experience with MPV. I cannot wait to see what you do in the future :)
