### ISSUE TITLE
Paste multiple urls at once

### ISSUE THREAD

**Issue by U1s2e3r4n5a6m7e** [Eisa01/mpv-scripts#36]
Hey! Thanks for the awesome scripts.

I tried the paste multiple urls at once but looks like doesn't work. I am using SmartCopyPaste Can you add this feature if it already does not exists?

When I paste the urls into mpv, it shows all the urls on osd as the following message:

> Pasted Into Playlist: 
> https://www.youtube.com/watch?v=ID1
> https://www.youtube.com/watch?v=ID2
> https://www.youtube.com/watch?v=ID3

But in reality **it only adding the first URL into the playlist**.

_Sorry about my language :P_

**Comment by Eisa01** [comment]
This feature is not available.
I need to to think of the separator that will be used for multiple urls. Space and new lines seem to be a good idea.

I'll see what I can do about it later

**Comment by Eisa01** [comment]
It is done now,
You can try SmartCopyPaste 3.1 Beta https://github.com/Eisa01/mpv-scripts/commit/d38c9153c1847f6cc1a49f03e721525481ca141d, it should support multi-paste. The separator is new line so it must be like the format you purposed
 ```
C:\Videos\Anime\One Piece (1999)\One Piece - S02E12 - 020 - [SDTV][MP3 2.0][XviD][K-F].ar.srt
THIS WILL BE IGNORED ;)
C:\Users\Eisa01\Desktop\Dragon Ball Kai 01.mkv
C:\Users\Eisa01\Desktop\Bleach 01 [SD].avi
C:\Videos\Anime\One Piece (1999)\One Piece - S01E02 - 002 - [SDTV][AAC 2.0][x264][K-F].en.srt
https://www.youtube.com/watch?v=ID1
https://www.youtube.com/watch?v=ID2
https://www.youtube.com/watch?v=ID3
C:\Users\Eisa01\Desktop\Bleach 02 [SD].avi
C:\Users\Eisa01\Desktop\Naruto - S01E01.mkv
```

It will add to playlist, appends subtitles, ignores files that doesn't exists or files that are unsupported, and play file with pasted time if no file is running.

**Comment by U1s2e3r4n5a6m7e** [comment]
Thank you for doing this.
I appreciate your hard work. I tried with urls and It works flawlessly.
