### ISSUE TITLE
SimpleUndo-2.5.lua:68: attempt to index global 'timer' (a nil value)

### ISSUE THREAD

**Issue by haarp** [Eisa01/mpv-scripts#4]
Hello,

just tried SimpleUndo 2.5 and it worked once. Can't get it working again now. mpv 0.29.1 says:

```
[SimpleUndo_2_5]
[SimpleUndo_2_5] stack traceback:
[SimpleUndo_2_5] 	mp.defaults:459: in function 'call_event_handlers'
[SimpleUndo_2_5] 	mp.defaults:496: in function 'dispatch_events'
[SimpleUndo_2_5] 	mp.defaults:452: in function <mp.defaults:451>
[SimpleUndo_2_5] 	[C]: at 0x55925d44bb00
[SimpleUndo_2_5] 	[C]: at 0x55925d44d170
[SimpleUndo_2_5] Lua error: /home/haarp/.config/mpv/scripts/SimpleUndo-2.5.lua:68: attempt to index global 'timer' (a nil value)
```

Thanks!

**Comment by Eisa01** [comment]
Are you using Linux or MAC OS?

**Comment by haarp** [comment]
Linux

**Comment by Eisa01** [comment]
It is a very strange one. Can you try to undo in different video and let me know if the issue is there?

**Comment by haarp** [comment]
Hmm, I think I can reproduce it. It seems to happen when you open directories in mpv instead of the tracks themselves.

**Comment by Eisa01** [comment]
Let me know if you are able to confirm it, I will also explore it when I have the time since I did not know about mpv capability to open directories.

**Comment by Eisa01** [comment]
If you are able to reproduce it, can you test this version and let me know if it fixes the issue
[SimpleUndo-2.5.1.lua.zip](https://github.com/Eisa01/mpv-scripts/files/3992012/SimpleUndo-2.5.1.lua.zip)

**Comment by gbstan** [comment]
I probably affect other scripts too.

**Comment by haarp** [comment]
> If you are able to reproduce it, can you test this version and let me know if it fixes the issue
> [SimpleUndo-2.5.1.lua.zip](https://github.com/Eisa01/mpv-scripts/files/3992012/SimpleUndo-2.5.1.lua.zip)

Yes, this version fixes the issue. Thanks!!

**Comment by Eisa01** [comment]
Amazing, also applied same fix to UndoRedo because it was affected with the same bug.
Issue closed ^ ^
