### ISSUE TITLE
Unable to paste youtube links (tried both ytdl and ytdlp)

### ISSUE THREAD

**Issue by NullCode1337** [Eisa01/mpv-scripts#41]
I have the same issue as #26 

Since I am on wayland, I set the copy & paste commands to 
![image](https://user-images.githubusercontent.com/70959549/154683826-569c3353-c1dc-4649-ba52-1305f5f30396.png)

yet, I keep getting the `Pasted unsupported item` error
Here's my neofetch if that helps:
![image](https://user-images.githubusercontent.com/70959549/154684024-fb161df9-0a79-478b-bb63-e9d6576c9fc5.png) 

`mpv-1:0.34.1-2`

**Comment by NullCode1337** [comment]
Sorry for being a nuisance, I forgot to edit `SmartCopyPaste.conf` and just edited `SmartCopyPaste.lua`

After editing both, the issue got fixed. Thanks for the awesome scripts

**Comment by Eisa01** [comment]
Perfect, though you only need to edit `.conf` file. Editing the `.lua` file works only if the `.conf` file doesn't exist
