### ISSUE TITLE
Add project tag mpv-script

### ISSUE THREAD

**Issue by stax76** [Eisa01/mpv-scripts#42]
I suggest adding the tag `mpv-script` because tags are an excellent way to find software.

https://github.com/topics/mpv-script

**Comment by Eisa01** [comment]
Thanks for the tip, I'll see how it can be added.

**Comment by stax76** [comment]
You can add it very easily via UI on the main readme page.

It's in the same dialog where you can edit the page about title.

**Comment by Eisa01** [comment]
Done
