### ISSUE TITLE
SimpleHistory: Along with the recent keybind, include all the files if it is in a playlist - Feature Request

### ISSUE THREAD

**Issue by Cananbolt** [Eisa01/mpv-scripts#43]
I was just wondering if there is a way to include all the files in the playlist and the recent file. So, in initial use when you quit a video from a playlist and open MPV again, once you press the keybind to resume the file, it will only show the file you were last on and none of the remaining files of the playlist, which made me think if it is possible to include all the files in the playlist along with the recent file.

**Comment by Eisa01** [comment]
I don't understand the request, please clarify.
Do you mean you want a new filter that works in certain way?

**Comment by Cananbolt** [comment]
> 

My apologies, basically I'd like the script to include all the files in a playlist. It shows the most recent file which works as intended. But as you said maybe add a new filter that includes not only the recent file but its playlist that follows.

For example, say I have a tv series called Teen Titans which has 65 episodes. If I were to watch the first episode and quit MPV, once I open MPV and press [Ctrl+r] the playlist will only contain the 1st episode and none of the rest. If it is possible I'd like a new filter to include all the episodes in the playlist along with the recent file.

**Comment by Eisa01** [comment]
I believe what you need has already been developed, you can use autoload script: https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua

This adds all the files related to the file you are playing to your playlist, keep me posted

**Comment by Cananbolt** [comment]
Yes with autoload it adds all files into the playlist, thank you so much for the help. I'm sorry for wasting your time.

**Comment by Eisa01** [comment]
Glad it's sorted
