### ISSUE TITLE
SimpleHistory: Add a keybind in the distinct protocol (or all, if possible) to completely delete an entry - Request

### ISSUE THREAD

**Issue by Cananbolt** [Eisa01/mpv-scripts#44]
Request to completely delete an entry.

For Example:
In distinct protocol, it shows
Teen Titans Episode 60

Once you press the keybind to delete it will find the last episode you've watched

For example, it may show...
Teen Titans Episode 59

Is there a way to completely delete an entry in the distinct protocol?

**Comment by Eisa01** [comment]
Yeah, if you are using 1.1.
- Open history without any filter <key>h</key>
- Search for teen titans using it's name or path to be more accurate if needed <key>ctrl+f</key>
- Press <key>ctrl+a</key> to highlight all
- Press <key>shift+del</key> to delete all highlighted.

**Comment by Cananbolt** [comment]
Yes that did it, but is there a way to unselect individual files. Ctrl+d unhighlights all but is there a keybind to unhighlight individually?

[Azmaan Kolondar - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1hkkea)	[1hkkea]

On March 31, 2022 at 2:29 GMT, Eisa01 ***@***.***> wrote:

Yeah, if you are using 1.1.

- Open history without any filter h
- Search for teen titans using it's name or path to be more accurate if needed ctrl+f
- Press ctrl+a to highlight all
- Press shift+del to delete all highlighted.

**Comment by Eisa01** [comment]
Yeah, press shift while navigating, e.g.: shift + down or shift + pgdwn and so on..

**Comment by Cananbolt** [comment]
Perfect, that did it. Thank you.

[Azmaan Kolondar - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1hknp7)	[1hknp7]

On March 31, 2022 at 3:40 GMT, Eisa01 ***@***.***> wrote:

Yeah, press shift while navigating, e.g.: shift + down or shift + pgdwn and so on..
