### ISSUE TITLE
文件名中有中文俄文的无法粘贴播放

### ISSUE THREAD

**Issue by RallyQ** [Eisa01/mpv-scripts#45]
英文名的文件可以添加到播放列表正常播放，中文俄文的视频文件无法播放
SmartCopyPaste.lua
win10 64位

**Comment by Eisa01** [comment]
我会仔细看看的。

I will look into it.
Translated by Google Translate.

**Comment by Eisa01** [comment]
在最新版本中解决

Resolved in latest release
Translated by Google Translate.

**Comment by RallyQ** [comment]
> 在最新版本中解决
> 
> 在最新版本中解决 由谷歌翻译翻译。
试了最新版，中文俄文还是不行，粘贴时提示文件不存在，file doesn't exist
英文文件名的能正常加入到播放列表

**Comment by Eisa01** [comment]
你能给我一个完整的路径示例吗，因为我尝试了中文文件名，它可以工作。

Can you give me a full path example, because I tried Chinese file names and it works.
Translated by Google Translate.

**Comment by RallyQ** [comment]
> 你能给我一个完整的路径示例吗，因为我尝试了中文文件名，它可以工作。
> 
> 你能给我一个完整的路径示例吗，因为我尝试了中文文件名，它可以工作。 由谷歌翻译翻译。

如 
f:\Download\测试_2022.mp4
