### ISSUE TITLE
Add it mplug script directory

### ISSUE THREAD

**Issue by z8512** [Eisa01/mpv-scripts#48]
Mplug is like a package manager but for mpv scripts.
Please add your script there (if already not there) and also installation instructions in manifest - https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

**Comment by Eisa01** [comment]
Searching for my script shows that it's already there.

**Comment by z8512** [comment]
Wonderful! 
But there's not installation method https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md#installation-method-install in the manifest! Please add in https://github.com/Nudin/mpv-script-directory/blob/master/mpv_script_directory.json#L2038
