### ISSUE TITLE
SmartHistory_1_5 sometimes throws an error

### ISSUE THREAD

**Issue by gbstan** [Eisa01/mpv-scripts#5]
It seems that sometimes (on youtube playlists for example) SmartHistory 1.5 throws an error.

Here is an example:

```

[SmartHistory_1_5] 
[SmartHistory_1_5] stack traceback:
[SmartHistory_1_5] 	...uy-bartstan/.config/mpv/scripts/SmartHistory-1.5.lua:48: in function 'handler'
[SmartHistory_1_5] 	mp.defaults:460: in function 'call_event_handlers'
[SmartHistory_1_5] 	mp.defaults:494: in function 'dispatch_events'
[SmartHistory_1_5] 	mp.defaults:453: in function <mp.defaults:452>
[SmartHistory_1_5] 	[C]: ?
[SmartHistory_1_5] 	[C]: ?
[SmartHistory_1_5] Lua error: ...uy-bartstan/.config/mpv/scripts/SmartHistory-1.5.lua:48: attempt to concatenate global 'filePath' (a nil value)
```

**Comment by gbstan** [comment]
Any way I can help debug this?

**Comment by Eisa01** [comment]
@gbstan Thank you for reporting the issue, however I was away for a month. The logs I believe are enough.

Can you test this version and let me know if it fixes the issue
[SmartHistory-1.5.1.txt](https://github.com/Eisa01/mpv-scripts/files/4087151/SmartHistory-1.5.1.txt)
rename it to .lua

**Comment by gbstan** [comment]
Yes, this seems to work!
