### ISSUE TITLE
When file has a ` then clipboard is empty

### ISSUE THREAD

**Issue by Max-Enrik** [Eisa01/mpv-scripts#54]
Hi,

I want to mention when a file has a ` then clipboard is empty how to clipboard a file path/file name.

Thank you.

**Comment by Eisa01** [comment]
Can you tell me which script you are using and what version?
Also mpv version and your Operating System.

**Comment by Max-Enrik** [comment]
Ah! Sorry, I forgot about them.

1. SmartCopyPaste_II v3.1
2. mpv 0.34
3. PC WINDOWS 10 x64

**Comment by Eisa01** [comment]
I cannot seem to replicate the issue, can you give me the full path along with the full file name?

**Comment by Max-Enrik** [comment]
When I remove the symbol between alphabets the script works like a charm. `a’s`

**Comment by Eisa01** [comment]
This symbol is working fine for me, I cannot seem to be able to reproduce it.
Perhaps you are using the version without unicode support.

Can you try updating the script?

**Comment by Max-Enrik** [comment]
I updated the script. Unfortunately, the problem remains. I think I should try it on a new computer for testing purposes. I will do that later.

**Comment by Eisa01** [comment]
You could also give me the console logs, just press <kbd>`<kbd> to backtrace the logs where the paste occurs.
Also the full filename and path could be helpful.

**Comment by Eisa01** [comment]
Closed as I am unable to reproduce.
