### ISSUE TITLE
Paste multiple links into MPV as different playlist entries?

### ISSUE THREAD

**Issue by MintMain21** [Eisa01/mpv-scripts#55]
Using the Foxytab extension, I can mass copy the links for youtube videos I have open in different tabs, and hypothetically paste them into MPV. Unfortunately, the player only loads the first link. 

While it is understandable that this might be an unavoidable consequence of working with MPV and otherwise unresolvable, I'd still appreciate a way to paste multiple links at once into MPV and have the player recognize them all as different links instead of a single link.

**Comment by Eisa01** [comment]
Pasting multiple links is supported,
The format should be as the following below:
```
C:\Videos\Anime\One Piece (1999)\One Piece - S02E12 - 020 - [SDTV][MP3 2.0][XviD][K-F].ar.srt
THIS WILL BE IGNORED ;)
C:\Users\Eisa01\Desktop\Dragon Ball Kai 01.mkv
C:\Users\Eisa01\Desktop\Bleach 01 [SD].avi
C:\Videos\Anime\One Piece (1999)\One Piece - S01E02 - 002 - [SDTV][AAC 2.0][x264][K-F].en.srt
https://www.youtube.com/watch?v=ID1
https://www.youtube.com/watch?v=ID2
https://www.youtube.com/watch?v=ID3
C:\Users\Eisa01\Desktop\Bleach 02 [SD].avi
C:\Users\Eisa01\Desktop\Naruto - S01E01.mkv
```

**Comment by MintMain21** [comment]
So.....is it supposed to separate links into separate videos by default, or is there something I need to change in the Lua file?

**Comment by Eisa01** [comment]
If you are using the latest version of the script, it should automatically add the videos into playlist.
If that is not working, try to provide me with the paste you're applying

**Comment by MintMain21** [comment]
https://iteroni.com/watch?v=Le8nJ3GbW_0 https://iteroni.com/watch?v=MRT3VBUcBNI https://iteroni.com/watch?v=ueTGP2jqQIE https://iteroni.com/watch?v=GHk07iGxCqc https://iteroni.com/watch?v=1VbauWINt30 https://iteroni.com/watch?v=r0Xfn3Bq3X8 https://iteroni.com/watch?v=gqoPf0V2LrA https://iteroni.com/watch?v=yV6NmyV12Uo https://iteroni.com/watch?v=pLSgkN49ZUI

Here's an example

**Comment by Eisa01** [comment]
You're using SmartCopyPaste or SmartCopyPaste_II?

**Comment by Eisa01** [comment]
It should work as part of 3.2 update.
It is now able to automatically identify multiple links (protocols) when pasting a long list to allow for space as a Seperator.
