### ISSUE TITLE
SimpleHistory.lua not backwards compatible with old mpvHistory.log

### ISSUE THREAD

**Issue by CynicusRex** [Eisa01/mpv-scripts#58]
When replacing the old smarthistory.lua with the new SimpleHistory.lua, the new version won't work if the old mpvHistory.log is still located in /.config/mpv/. It doesn't even throw an error message.

Moreover, because my old version mentions "Version: 1.7.1" and the new version mentions "Version: 1.1", I incorrectly assumed that the new one was a deprecated old version.

**Comment by Eisa01** [comment]
Sorry for that. Backward incompatibility is mentioned in the 2.0 release.

Writing backwards compatibility code will result in some unnecessary checks, so I decided to drop it.

I'll need to check why I didn't add an error message though, will keep issue open until then..
