### ISSUE TITLE
SimpleHistory: Automatically Resume Last Loaded Playback without any Keybind

### ISSUE THREAD

**Issue by Cananbolt** [Eisa01/mpv-scripts#60]
I was wondering if it would be possible to include an option to automatically resume your last playback (if it was saved) without having to press any keybinds.

**Comment by Eisa01** [comment]
You want it to automatically start when launching mpv?

**Comment by Cananbolt** [comment]
Only if the file has a time slot saved. For example, say if I stopped at 5:05 in a video. Instead of using the history_resume_keybind, it would automatically go to 5:05 when I go back to watch the video.

**Comment by Eisa01** [comment]
There will usually always be a time slot, if you exit nearing the end or the beginning of a video, then it will resume from there. Maybe there is a workaround for that, so I check if its in the first 10% or after the last 10% of a video then it ignores this behavior.

However, for now, In the rare cases where there are no time slot, what do you want the action to be?

**Comment by Cananbolt** [comment]
If there is a time slot saved, which always is the case for me, automatically resume playback without the use of a keybind, 

And if on the very very off chance there is no time slot, let it run as the default setting, which is to run the video from the beginning.

**Comment by Cananbolt** [comment]
I don't believe, I was clear with this request. I apologize. 

Say if I am currently watching a video and the time slot was saved for 5:05. If I go back to the previous video in the playlist just to see the end of the video and then return to the video I left at 5:05, it would tell me to Press the history_resume_keybind. I would like it to automatically resume the playback from where I left off, without needing to press the keybind.

**Comment by Eisa01** [comment]
I see, the resume notification only happens when you have watched at least 5% of a video.
I can create an option in the conf, of the 5% behavior. So you will get to choose to get notification, or to automatically resume instead.
Is that what you need?

**Comment by Cananbolt** [comment]
Exactly automatically resume the playback. I really am sorry for making this so confusing.

**Comment by Eisa01** [comment]
No worries, I'll see what I can do about it

**Comment by Cananbolt** [comment]
Also in the script at line 17 where it says
> resume_notification_threshold = 2, --0 to always show a resume notification when the same video has been played previously, a value such as 5 will only show the resume notification if the last played time starts after 5% of the video and ends before completion by 5%

If you change
`resume_notification_threshold = 2`

to
`resume_notification_threshold = 0`

You can always see the resume notification.

**Comment by Cananbolt** [comment]
Then I do not believe we have to worry about the percentage of the video which may make it easier.

**Comment by Cananbolt** [comment]
> No worries, I'll see what I can do about it

Thank you so much!

**Comment by Eisa01** [comment]
Yeah, it is configurable. I'll make it more customizable so instead of 
`resume_notification_threshold = 2`
It will be
`resume_option_start_threshold = 2`
`resume_option_end_threshold = 2`
This will enable you to customize the start and end separately instead of doing it both together.
Also, instead of `resume_notification = yes` it will be `resume_option` and you will get to choose `resume_option =` `notification` or `force_resume`

**Comment by Cananbolt** [comment]
Sounds like exactly what I asked for. I really really do appreciate, your patience. I can't thank you enough

**Comment by Eisa01** [comment]
I have made the changes, I have kept the threshold the same, having two values made it complex.
Change the option to `force` in the conf file and it should work. Let me know if this solves it for you

**Comment by Cananbolt** [comment]
Just did a quick test, and this is exactly what I wanted. Thank you so much.

**Comment by vitormathews** [comment]
I tried the reccommended settings but couldn't get it to auto load the latest played file when starting MPV. :(
Here is my complete settings file: https://pastebin.com/LJqkS0K7

**Comment by Cananbolt** [comment]
> I tried the reccommended settings but couldn't get it to auto load the latest played file when starting MPV. :( Here is my complete settings file: https://pastebin.com/LJqkS0K7

You should make a new issue about this. I too am having the same problem. But for me the auto resume does work, but it's a bit inconsistent.

**Comment by Eisa01** [comment]
@vitormathews 
Are you sure that the settings are reflecting correctly? Like of you make other changes in the config file, do you see them reflecting?

@Cananbolt 
Hmm, can you perhaps identify some use cases where it doesn't work so I can troubleshoot it?

**Comment by vitormathews** [comment]
> Are you sure that the settings are reflecting correctly? Like of you make other changes in the config file, do you see them reflecting?

Yes, I changed some keybinds and the changes were reflected.

**Comment by Cananbolt** [comment]
> @vitormathews Are you sure that the settings are reflecting correctly? Like of you make other changes in the config file, do you see them reflecting?
> 
> @Cananbolt Hmm, can you perhaps identify some use cases where it doesn't work so I can troubleshoot it?

For whatever reason, I think it has to do with a couple of the script's lines. With version 1.1.2 the auto feature did not work. However, 1.1.1 the one I am currently using does work at times but still inconsistent.

From what I found these added items to version 1.1.2 stopped making the auto feature from working. I'm not exactly sure which lines are causing the script to not work. 

line 978-979
	utils.shared_script_property_set("simplehistory-menu-open", "yes")
	if o.toggle_idlescreen then mp.commandv('script-message', 'osc-idlescreen', 'yes', 'no_osd') end

line 	1641-1642
	utils.shared_script_property_set("simplehistory-menu-open", "no")
	if o.toggle_idlescreen then mp.commandv('script-message', 'osc-idlescreen', 'yes', 'no_osd') end

line 2009
	if not list_contents or not list_contents[1] then return end

line 2221-2223
	logTime = (mp.get_property_number('time-pos') or 0)
end)
mp.register_event('end-file', function()--1.1.3# use end-file instead so that it doesn't cause crash while seeking ( i am able to run big functions here)

**Comment by Cananbolt** [comment]
> @vitormathews Are you sure that the settings are reflecting correctly? Like of you make other changes in the config file, do you see them reflecting?
> 
> @Cananbolt Hmm, can you perhaps identify some use cases where it doesn't work so I can troubleshoot it?

Now the version that I use simply does not include any of those features (1.1.1). However, it is inconsistent. An example is, if I am watching:

1. Avatar Ep 1 (time at 5:05)
2. Moved on to Ep 2
3. Went back to Ep 1 (nothing is wrong the first time)
4. Repeat Steps 2 & 3, eventually, the force resume function will not work; Ep 1 would start at the beginning of the video and I would have to press the keybind to restore my last posiiton.

**Comment by Eisa01** [comment]
Ah, I cannot seem to replicate it. It is working perfectly for me with every test.

**Comment by Eisa01** [comment]
I have pushed a commit; it has some optimizations that has to do with forcing resume, can you test and let me know if it fixes it for you?

**Comment by Cananbolt** [comment]
Yes!! tested out version 1.1.4 and it works great. Did multiple scenarios which previously would reset the video at random moments, but now it seems to work very consistently. It may be best to wait for @vitormathews response as well to have more opinions, but for my initial testing, it seems to work great. Thanks for the fix.

**Comment by vitormathews** [comment]
> I have pushed a commit; it has some optimizations that has to do with forcing resume, can you test and let me know if it fixes it for you? I have no way of knowing since I cannot seem able to break it...

Yet not working for me. It should automatically open the most recent video when I open a MPV window, right? Like [keep-session.lua](https://github.com/CogentRedTester/mpv-scripts/blob/master/keep-session.lua) does. Or did I get it wrong?

Btw, I'm on Windows 10 21H2 19044.2364.

**Comment by Eisa01** [comment]
Ah no, what it does is automatically resume when you open a file.
Say you have move1.mp4, you reach minute 30.
When you open movie1.mp4 again, it will start from minute 30.

**Comment by vitormathews** [comment]
> Ah no, what it does is automatically resume when you open a file. Say you have move1.mp4, you reach minute 30. When you open movie1.mp4 again, it will start from minute 30.

Oh, got it, sorry. But doesn't ```save-position-on-quit``` already do this?

> open the most recent video when I open a MPV window

So, I let this as a feature request haha.

**Comment by Eisa01** [comment]
> Oh, got it, sorry. But doesn't `save-position-on-quit` already do this?
Yeah, however, this allows for threshold, and should work no matter how the video was closed. So, it makes sense for users who are not depending on `save-position-on-quit`

Also, 
continued discussion for your feature on #73
