### ISSUE TITLE
[Linux] SmartCopyPaste II always tries to use xclip

### ISSUE THREAD

**Issue by luke876** [Eisa01/mpv-scripts#61]
I have changed the linux_copy and linux_paste options in script opts and the script file itself. There is no mention of xclip anywhere in the entire script file. Regardless of this it still attempts to use xclip.
```
[SmartCopyPaste] Pasting... 
sh: 1: xclip: not found
[SmartCopyPaste] Failed to paste into mpv, pasted item shown below is unsupported possibly due to configuration:
```

**Comment by Eisa01** [comment]
I am seeing this error is generated from SmartCopyPaste and not SmartCopyPaste_II
did you install both?

**Comment by luke876** [comment]
I was using the config file for spartcopypaste 2 with the original smartcopypaste script. Sorry about that!
