### ISSUE TITLE
Add a functionality for including categories for Bookmarking

### ISSUE THREAD

**Issue by Kayizoku** [Eisa01/mpv-scripts#62]
Basically, if you bookmark now some movies and tv shows they will be all mixed up and there's no way of knowing what is what. But what if you could add in a category directly in MPV that is named "movies" or "tv shows", then you can choose where to place that bookmark, keeping it cleaner and neater as a result. 

So the function would first allow you to create a virtual folder that you can access with the log manager, and these will be used for bookmarks.

It would be a super neat future to have

**Comment by Eisa01** [comment]
I thought the playlist script was the solution for this, did it not work well for you and why?

**Comment by Kayizoku** [comment]
> I thought the playlist script was the solution for this, did it not work well for you and why?

Nope, this is something else. I just want it to separate bookmarks for different files, whether its movies, tv shows or anime

**Comment by Eisa01** [comment]
I see, how do you imagine the category works, to be intuitive.
How will you assign the category and how will you access it?

**Comment by Kayizoku** [comment]
I am thinking you will have to make actual live folders called "tv shows" or "movies" were you will be bookmarking the respective things. Of course, a parent folder needs to be included to isolate it from other folders and files. Then you somehow need a way to link the bookmarks to those sub-folders in that parent folder to make it appear like it's showing up there. I know Windows got a symbolic link feature so maybe you would have to use that somehow but I am not sure how.

Otherwise, I don't know if this is possible, but maybe create a new .txt files for the respective "tv shows" and "movies" section and inside of those respective .txt files you write the file you are trying to bookmark. But somehow you need a way to open up your preferred section, but I am not certain how that would work. 

After all that's done, there needs to be a way to virtually show it in MPV, so you can select, delete, edit or add a new bookmark category.

This is the rough scope of it. I hope I am making sense and apologize in advance if I don't lol

**Comment by Eisa01** [comment]
No I am not talking about mechanics, I am talking about within mpv as a user.

Im thinking in the conf file, you create the categories.
`Categories= "tv shows",  "movies", "anime"`
Then for example you press f1 on a bookmarked item to assign and cycle between different categories.
This is one case.

Another case where we can assign f1 to a category f2 to a different category, etc.
`Categories= "tv shows - f1",  "movies - f2", "anime - f3"`

These are quick thoughts when brainstorming, let me know if you have other ideas so I can see which makes more sense

**Comment by Kayizoku** [comment]
Oh, wow. I am delighted that you are actually considering it.

My bad. In that case, I feel like the first option would be the most intuitive as it takes less than a second to cycle through different categories but this honestly depends on the user. But if the user creates more than five categories, it could end up being redundant and tiresome.

For that, it would be neater if the category showed up as virtual folders like a list so you can cycle through and enter them using your keyboard. The behavior would be similar to opening up a folder and seeing the files that are bookmarked in there. This script - https://github.com/CogentRedTester/mpv-file-browser can be used as reference for this feature.

**Comment by Eisa01** [comment]
The problem with that is that it will make each category at least 3 steps away.
First you have to access a folder > second you have to select a category > third you have to enter the bookmark from that category.
(It will eliminate quick access). I like simplicity and ease of access.

I am still thinking on the best way of how to display categories, and how to make them easy to access.

**Comment by Kayizoku** [comment]
> The problem with that is that it will make each category at least 3 steps away. First you have to access a folder > second you have to select a category > third you have to enter the bookmark from that category. (It will eliminate quick access). I like simplicity and ease of access.
> 
> I am still thinking on the best way of how to display categories, and how to make them easy to access.

Yeah, you are right. In terms of accessibility it does suffer a lot. But I am sure there's a solution out there somewhere we've yet to find. In any case, if this gets implemented it would be quite nice addition. I thank you once again for considering my ideas. I feel like I have asked you a lot about these ngl

**Comment by Eisa01** [comment]
Guess you are no.1 customer for my scripts.
Joking aside, I quite appreciate QoL improvements feedback.
You seem to come up with ideas that I have not thought of at all, the stuff that are missing, which are quite good additions.

Guess you use my scripts more than I do, and find the improvements needed. Keep the good ideas up👍

**Comment by Kayizoku** [comment]
That's what happens when you make a batch of wonderful scripts. I use them so often that at times I don't even realize it, it's all muscle memory and things feel so wrong when I don't have them with me. 

MPV should definitely consider adding some of these by default.

Thanks for the compliment. I'll keep on sharing if there's anything else in the near future. I think it's suffices to say that your scripts are my favorite :)

**Comment by Kayizoku** [comment]
If you need any help with testing when you eventually try to implement it. I'd be more than happy to lend a hand :)

**Comment by Eisa01** [comment]
Groups functionality and other enhancements are now completed as part of SimpleBookmark 1.2 changes.
You can get the latest conf file and the script for the features.

**Things to know about:**
Assigning groups can be done in two ways:

1. One assigning the group name, followed by the keybind. `["TV Shows", "ctrl+1"]`. This is good for people who have multiple groups. Or you can just assign the group names without specific keybind `["TV Shows"], ["Movies"]` (good if you have less groups)

2. Whether you assign keybind to group or not, you can add to groups by pressing ["Ctrl+g"]. It will automatically find and cycle through all your created groups with each keypress.

**How to access groups:**

You can access all items that are grouped by using `"groups"` filter. You can access specific groups by using `"/:group%Group Name%"` filter.

These filters can be used anywhere in the config file, where the filter parameter is accepted, config sample.: 
1. if you want immediate access to a specific group from anywhere: `open_list_keybind` `["t", "/:group%TV Shows%"]`
2. If you want to jump to specific filter when the list is open: `list_filter_jump_keybind` `["t", "/:group%TV Shows%"]`
3. Or my favorite, just press the left and right arrow keys to go to different filters, based on `filters_and_sequence` `"/:group%TV Shows%`

**Comment by Kayizoku** [comment]
This is incredible. I can hardly believe this is a thing now. 
This will save so much time and make life so much easier. 

I even got an idea for improvements. I noticed you can remove in a batch but not add several items to group at once. 

Otherwise, this is exactly what I wanted. 

Thank you for your great work :D

**Comment by Eisa01** [comment]
I just discovered serious bug, do not use search while adding to groups or keybinds. If you do it will clear your bookmarks. I'll have a look at it maybe by tomorrow to find a fix.

**Comment by Kayizoku** [comment]
Ah, so that's why I lost all my bookmarks just now. I thought I cleared them by myself on accident, but no worries. I always take backups so I lost nothing.

**Comment by Kayizoku** [comment]
It would be nice to complement the feature to batch remove entries at once and trust me it would help even more to save time.

I also wondered if there's a way to show all the sections at once, like a list on screen. If you have many bookmarks section it could be good to know what sections you have. In some cases, it might even be easier to just pop it open and then scroll and click right into it. Altough, the shortcut option is already instantaneous, the only caveat is you have to remember the shortcuts. It's not difficult with five bookmark section, but if you have more, it definitely would be an annoyance, so just something to consider.

Another way to make thing easier, like bookmarking to different sections. For example, if you press k to open "tv shows", then  when you press the bookmark key CTRL+b, it actually bookmarks to "tv shows" and not to the unfiltered section of "all."

Hopefully, I am making some sense and apologize in advance if I don't. Thank you once again :)

**Comment by Eisa01** [comment]
> I also wondered if there's a way to show all the sections at once, like a list on screen. If you have many bookmarks section it could be good to know what sections you have. In some cases, it might even be easier to just pop it open and then scroll and click right into it. Altough, the shortcut option is already instantaneous, the only caveat is you have to remember the shortcuts. It's not difficult with five bookmark section, but if you have more, it definitely would be an annoyance, so just something to consider.

Why not use arrow keys and put the groups to be the first thing that appear? You can have the right key arrow have all the groups nearby, and you can arrange other filters to be positioned at the end so that they are applied by the left arrow.
You can test it and let me know your thoughts on this.

> Another way to make thing easier, like bookmarking to different sections. For example, if you press k to open "tv shows", then when you press the bookmark key CTRL+b, it actually bookmarks to "tv shows" and not to the unfiltered section of "all."

I'll see if this could work with the current logic of writing logs.

**Comment by Kayizoku** [comment]
>Why not use filters_and_sequence arrow keys and put the groups to be the first thing that appear? You can have the right key arrow have all the groups nearby, and you can arrange other filters to be positioned at the end so that they are applied by the left arrow.
You can test it and let me know your thoughts on this.

Oh, that's what I am currently doing and it works nice with a few bookmark sections but if there's many more it can be time consuming and even get annoying. Altough, I guess the biggest advantage to having a list is you can see all your bookmark sections so you don't have to remember them, but you still have to use the arrow-keys to get to them but personally, I think that would work better in the long run. Because having more of those bookmark sections means you have to have more shortcuts to remember and more of those bookmarks to remember. That's why I think displaying as a list would be more suitable as you can see all your options and pick which you want more easily and effortlessly.

**Comment by Kayizoku** [comment]
> Makes sense, I will consider it. It could be a Filters folder, and inside the config file you can define which filters you want to display.

That sounds like a good plan. I am looking forward to these updates whenever they might come. Take your time

**Comment by Eisa01** [comment]
For now, I believe the issue related to losing logged items is resolved. https://github.com/Eisa01/mpv-scripts/commit/556514879dcb306f6c024aee61a501c8240197b6

Also adding highlighted items to group is possible, either via cycle or via specific keybind.
`list_group_add_cycle_highlighted_keybind=[[ ["ctrl+G"] ]]` or the third parameter refers to highlighted keybind `groups_list_and_keybind =[[[ ["TV Shows", "ctrl+1", "ctrl+!"] ]]]`

I have made major backend changes; it allowed me to enhance the functions overall and resolve some nitpicks I had. 
Also hopefully, this will allow me to create the virtual folders, but further testing is needed.

I will appreciate if you could test it and mess around with it and try to break it, so if there is an issue, I could fix it.

**Comment by Kayizoku** [comment]
I tried lots of thing and it didn't seem to break so far. So things are working as they should. But there is one problem. I noticed that I am unable to create any more groups, besides manipulating the pre-defined ones. It won't register on its defined shortcut-key or even show up when clicking the arrow key. But that's likely by design as you are testing virtual folders, right?

I also would like to propose another change. 

Right now if you add items to a group, say "tv shows", all those groups added items are shown in the "unfiltered" section of all. But I think it would be better to have them hide the group items from the unfiltered section as we already have a filtered option for groups, so if we need to manipulate the group items we could go in there. Because this way if you need delete to bookmarks, you can delete them safely without messing up your groups.

**Comment by Eisa01** [comment]
> I tried lots of thing and it didn't seem to break so far. So things are working as they should. But I will continue testing and let you know the second I spot something wrong.
Perfect, as it stands, I'll close this.

**Comment by Eisa01** [comment]
>I tried lots of thing and it didn't seem to break so far. So things are working as they should. But I will continue testing and let you know the second I spot something wrong.

I'll close this for now then.

I also would like to propose another change.

> Right now if you add items to a group, say "tv shows", all those groups added items are shown in the "unfiltered" section of all. But I think it would be better to have them hide the group items from the unfiltered section as we already have a filtered option for groups, so if we need to manipulate the group items we could go in there. Because this way if you need delete to bookmarks, you can delete them safely without messing up your groups.

Actually, changing the filter of 'all' is not the right way. 
However, this can still be done. To proceed with your suggestion, I will attempt to give the option to deduct a filter from any filter. For example, you have `all`, and you want to omit `groups`, then you will use `all-groups`.
I have created an issue to track this: https://github.com/Eisa01/mpv-scripts/issues/66
Also for the virtual directory you suggested: https://github.com/Eisa01/mpv-scripts/issues/65
