### ISSUE TITLE
Pasting URLs causes MPV to close

### ISSUE THREAD

**Issue by sonalvrioss-svyatos** [Eisa01/mpv-scripts#63]
Hi, I tried pasting Youtube URLs into MPV and it simply closes without doing anything. I have tried both SmartCopyPaste and SmartCopyPasteII and both don't work. My MPV version is mpv-x86_64-v3-20221016-git-cdcbd73.

**Comment by Eisa01** [comment]
Does dragging the URL works?
If not this you're probably missing [youtube-dl](http://ytdl-org.github.io/youtube-dl/download.html) in mpv folder

**Comment by sonalvrioss-svyatos** [comment]
It's working now. Thanks.
