### ISSUE TITLE
SimpleBookmark: Option to omit specific filters

### ISSUE THREAD

**Issue by Eisa01** [Eisa01/mpv-scripts#66]
To allow additional filters customization, there should be a way to omit filters from a filter.
E.g.: `all-groups`.
The above configuration is a sample for `all` filter with `groups` omitted.

**Comment by Kayizoku** [comment]
Prevent duplicates if the file already exist in a group, don't remove it's current status, only update the new time.

**Comment by Eisa01** [comment]
Do you mean if `same_entry_limit` is set to `0`, you want it to update the bookmark with the new time while keeping the group and keybind?

**Comment by Kayizoku** [comment]
That's right, I noticed the new changes affected some of those options. So decided to add a note for it

**Comment by Eisa01** [comment]
Filters are now stackable and omittable https://github.com/Eisa01/mpv-scripts/commit/2b2b456825d64688341c4e7bd8343b8c22b4be21. This makes filters way more diverse.
So you can do something like `all%-%keybinds%-%groups` or you can do `keybinds%+%groups`


Let me know if this solves this issue for you as well, also you can open other issues for things you noticed.

**Comment by Kayizoku** [comment]
It's working as it should and I noticed nothing alarming so far. I am able to stack and omit filters as I want. The only little thing I noticed is that even by putting same-entry to 0 I am still unable to make it so it won't update the group-items if I by mistake bookmark a file that's already bookmarked into a group. I've also noticed that while marking a lot of files for deletion or adding to a group, the only way to clear is to exit out of the bookmark log manager but this makes it so you lose your position and have to scroll to that position again, which can get quite tiresome and annoying quickly.

**Comment by Eisa01** [comment]
Yeah, this update didn't include a change for updating a bookmarked item. The behavior just replaces the current item with a fully new one. I'll see about updating instead of just overwriting

**Comment by Eisa01** [comment]
Also, regarding removing highlights; you can press Ctrl+d or Ctrl+a twice to remove all highlights

**Comment by Eisa01** [comment]
@Kayizoku

**Comment by Kayizoku** [comment]
> Also, regarding removing highlights; you can press Ctrl+d or Ctrl+a twice to remove all highlights

NIce, thank you. I didn't know that, I found another way by just pressing arrow key to deselect it but this is much better.
