### ISSUE TITLE
SimpleBookmark: Update Entry on Save Instead of Overwriting

### ISSUE THREAD

**Issue by Eisa01** [Eisa01/mpv-scripts#67]
When saving new bookmark entry for an existing item, it should update the entry with existing slot, and groups.
Perhaps this should be a configurable option so user could decide that each new entry should be counted as new, or to update existing entry.

(This is still an idea because the configuration file is already big enough)..

**Comment by Eisa01** [comment]
Closed for now as it does not seem that important, especially since this is only the case when overwriting entries. Could re-open in the future if saw that there is a need.

**Comment by Eisa01** [comment]
Hi @Kayizoku, is this still needed?

**Comment by Kayizoku** [comment]
> Hi @Kayizoku, is this still needed?

I would appreciate this feature, but it's no issue if its not implemented :)

**Comment by Eisa01** [comment]
I will work on it, it will be necessary I guess. Especially after migrating changes to other scripts.

**Comment by Eisa01** [comment]
@Kayizoku should be done now, you can test with the updated config and let me know the results.

**Comment by Kayizoku** [comment]
> @Kayizoku should be done now

My apologies, been a bit busy. But I can confirm its working. Thank you :)
