### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by LampPrinter** [Eisa01/mpv-scripts#68]
<img width="1044" alt="iShot_2022-11-22_15 48 07" src="https://user-images.githubusercontent.com/7559328/203288792-64c26532-b18b-4fb8-826a-e3ca97a335e9.png">

The photo explains the issue.

I am using "uosc" UI.

**Comment by Eisa01** [comment]
Perhaps the custom fonts in uosc UI do not contain icons.
I will be attempting a test from my side later, can you also provide me with your OS, mpv version, and any other add-ons or custom fonts if you are using

**Comment by LampPrinter** [comment]
> Perhaps the custom fonts in uosc UI do not contain icons. I will be attempting a test from my side later, can you also provide me with your OS, mpv version, and any other add-ons or custom fonts if you are using

MacOS 13
M1 MacBook Apple Silicon
MPV Version 0.35

No custom fonts. I only have 2 files in font folder that came with UOSC.
Actually, I removed everything. All scripts and fonts.
Icons still do not show up. Maybe you are using a special font?

**Comment by Eisa01** [comment]
You can customize it with emojis if that is available in MAC OS. Go to the conf file and you will see an option for header_text. Replace the icon that is not being displayed with a 🕘 clock icon or something similar

**Comment by LampPrinter** [comment]
> You can customize it with emojis if that is available in MAC OS. Go to the conf file and you will see an option for header_text. Replace the icon that is not being displayed with a 🕘 clock icon or something similar
> 
> Test that and let me know how it goes for you

I tried this earlier already. Emojis show up fine in the text editor. It is just in MPV they are not showing up.

**Comment by Eisa01** [comment]
Did you try removing the icons just to see if the config changes are reflecting correctly?

To activate search:
`Ctrl+f` is the default keybind for activating search.
You can also remap it to `meta+f` since you're using MAC

**Comment by LampPrinter** [comment]
> Did you try removing the icons just to see if the config changes are reflecting correctly?
> 
> To activate search: `Ctrl+f` is the default keybind for activating search. You can also remap it to `meta+f` since you're using MAC, find `list_search_activate` in the config for customization

Yes, I replaced the icons with text base emojis like ⧗ . Looks good now.
Are there any other option besides "list_alignment" to fine tune the location?

I like top left corner alignment but it seems to interfere with OSD messages.
Slightly lower but still top left alignment will be perfect.

**Comment by Eisa01** [comment]
In the config `parse_heaser` add ` \\N` before the text, as many times as you want to increase the vertical position.

**Comment by Eisa01** [comment]
Since text emojis are working, I will be closing this issue.

**Comment by LampPrinter** [comment]
Just one more query.
The protocols history seems to be getting saved fine.
Eg.
[Thursday/November 24/11/2022 22:22:49] "Arch Linux Updates Keep Breaking Packages (I've Given Up On Pacman!)" | https://www.youtube.com/watch?v=tgbpNuOfFQM | length=857.761 | time=25.45

But when I open a protocol recent item from Simple History, MPV just crashes.
Is there some special MPV setting required?

**Comment by Eisa01** [comment]
I think one of the mpv you are mentioning is without youtube_dl extension, you need youtube_dl for youtube links and many other urls.

**Comment by LampPrinter** [comment]
> I think one of the mpv you are mentioning is without youtube_dl extension, you need youtube_dl for youtube links and many other urls.

I have set it to use YT-DLP and everything is working fine. Videos play fine and get stored in Simple History fine.
What I meant was when opening a past opened "URL" from Simple History app crashes.

What is weird is if I open MPV app though terminal, Simple History works fine with URLs too.
Probably some weird MacOS behaviour.

**Comment by Eisa01** [comment]
I believe it should behave the same.
Can you try dragging a URL into mpv when mpv is not launched through terminal.
Just to see if URL causes crashes

**Comment by LampPrinter** [comment]
Nice catch.
Dragging URL crashes MPV.
But when MPV is launched with terminal using "/Applications/mpv.app/Contents/MacOS/mpv", Dragging URL works fine.

**Comment by Eisa01** [comment]
I think it's not able to reach your YT-DLP when it's not launched through terminal. Try messing around with that

**Comment by LampPrinter** [comment]
> I think it's not able to reach your YT-DLP when it's not launched through terminal. Try messing around with that

Is there any way to collect logs or something?

**Comment by Eisa01** [comment]
At this stage, i think it is better if you open an issue in mpv main repository for their support
