### ISSUE TITLE
Simple History - If you stop playback, you can not resume latest item

### ISSUE THREAD

**Issue by LampPrinter** [Eisa01/mpv-scripts#69]
idle=yes

When I stop playback of a file, Simple History can not resume last item.
It can play second last and all others.

Solution -
Close and restart mpv

**Comment by Eisa01** [comment]
Can you show me all of your config
And are you trying to resume through the list and it's not working after pressing `q`?

**Comment by LampPrinter** [comment]
Do you want my Simple History.conf file?

stop  # stop playback (quit or enter idle mode)

I have assigned 'q' to stop playback and turned idle mode on.
So when I stop playback, the idle mode activates with Simple History showing. I can not resume the latest item 1. It says loaded but nothing happens.
But I can resume number 2. 3. and so on.

Quitting mpv completely and restarting solves the issue.

**Comment by Eisa01** [comment]
I'li see, thanks for the clarification.
I'll try to replicate and write a hotfix for the issue

**Comment by Eisa01** [comment]
I have added a hotfix for the issue, update the script and try it.
it should be resolved now. However, I'll keep this open until I migrate it to the other scripts
