### ISSUE TITLE
Support user-added link types

### ISSUE THREAD

**Issue by noctuid** [Eisa01/mpv-scripts#7]
I'm using another script that adds support for magnet links, for example. It would be nice if there was setting where you could provide a string to match against (e.g. `magnet:`). If the clipboard contents match, it would just take the default behavior instead of failing (`mp.commandv('loadfile', videoFile, 'append-play')` for `paste-playlist`).

**Comment by Eisa01** [comment]
@noctuid 
I have added a new function linked to an array that makes the protocols definable.

Well what it means is that now you a setting to add whatever protocols you like
[SmartCopyPaste-II-2.1.txt](https://github.com/Eisa01/mpv-scripts/files/4087115/SmartCopyPaste-II-2.1.txt)

I have already added to it https and magnet. You can modify it further to your needs

This version also should fix your other issue https://github.com/Eisa01/mpv-scripts/issues/6

Please do test and let me know so I close this issue ^ ^

**Comment by noctuid** [comment]
Thanks! Yeah that works correctly for both issues.
