### ISSUE TITLE
Simple History-'history_blacklist' Doesn't apply to sub folders.

### ISSUE THREAD

**Issue by yeezylife** [Eisa01/mpv-scripts#70]
For example, if I use `history_blacklist=["d:\\nolog\\]` ,  a video file under d:\nolog\ [FLsnow&TGTDS][Eden_of_The_East][FULLHD][BDrip] will still be loged.

And that doesn't seems right, because a lot movie/anime/TV episodes are under a folder. It's impossible to add them into 'SimpleHistory.conf' file everytime I download something under a folder.

I'm on windows 11 64bit btw.

**Comment by Eisa01** [comment]
Hi can you clarify which os your scenario from the 3 below:
Do you need all subfolders under nolog to be blacklisted?
Or do you require only the nolog folder to be blacklisted?
Or is it both you want nolog folder and all subfolders under nolog?

**Comment by yeezylife** [comment]
Hi, I think I want ‘both nolog folder and all subfolders under nologed’.

I changed the configuration from the conf.

**Comment by Eisa01** [comment]
> Are you changing the configuration from the conf file or from the lua script? If you are using the conf file then it is only 1 `\` `d:\nolog\` also try without the final \ so it will be `d:\nolog`

I edited my comment, in case you missed it. Apply it and let me know how it goes

**Comment by yeezylife** [comment]
> I edited my comment, in case you missed it. Apply it and let me know how it goes

OK, testing both d:\nolog\ and d:\nolog now

**Comment by yeezylife** [comment]
And both d:\nolog\ and d:\nolog works as intended, video under subfolders doesn't get loged anymore.

I only use 2 `\`s because it's written this way in the examples in the conf:  ‘e.g.: ["c:\\users\\eisa01\\desktop", "c:\\temp\\naruto-01.mp4"’

Thank you for your resbponse!

**Comment by Eisa01** [comment]
Qh must've been my copy-paste mistake. I'll fix the sample. Thanks for bringing it to my attention.

**Comment by yeezylife** [comment]
Hi, sorry I have to reopen this. It's still a problem.

When I use `history_blacklist=["d:\nolog"]` or `history_blacklist=["d:\nolog\"]`  (it's the only line that I change from the original SimpleHistory.conf)

It just breaks the script , so of course it won't log subfolder, it won't log anything at all...
![screen](https://user-images.githubusercontent.com/30175425/204467387-a5ef1073-2793-448b-8126-d4e375bed59e.jpg)

If I want the script to work, I just have to change that line in the conf file into `history_blacklist=["d:\\nolog"]` (with 2 `\`) 
This way I won't get any error message in the console,but it just log everything I played in the subfolder like before, back to square one...

**Comment by yeezylife** [comment]
I tried changed it from the lua file,same problem.
I think 2 `\` is right (with lua or conf), it just will log anything you played in the subfolder.

**Comment by Eisa01** [comment]
I'll check it, thanks for updating

**Comment by Eisa01** [comment]
Which mpv version you are using?

**Comment by yeezylife** [comment]
> Which mpv version you are using?

It's shinchiro's build
mpv-x86_64-v3-20221120-git-f10b24e.7z | 2022-11-20




</body>
</html>[mpv-x86_64-v3-20221120-git-f10b24e.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20221120-git-f10b24e.7z/download)	2022-11-20

**Comment by Eisa01** [comment]
After reviewing the code there was no feature for subfolders, but it is available now in 1.1.2. Update the script and try it.

If you want both nolog and any subdirectory, then add the following into the conf file:
`"d:\\nolog", "d:\\nolog\\*"`, 

FYI:
Adding a `\\*` after a directory will make all subfolders (recursively) blacklisted
`d:\\nolog\\*` will add the following into blacklist `d:\\nolog\\anyfolder`, `d:\\nolog\\anyfolder\\anysubfolders\\...`

**Comment by yeezylife** [comment]
Works fine now!
