### ISSUE TITLE
SimpleHistory: mpv crashes when loading new file while seeking 

### ISSUE THREAD

**Issue by LampPrinter** [Eisa01/mpv-scripts#72]
Very weird issue.

To replicate, when you are about to reach the end of file, try a fast swipe to the right to seek forward. Or just keep holding the RIGHT key.
MPV would crash.
If you do not swipe forward and let the video end normally, MPV does not crash and next file loads automatically.

I have removed all scripts and it only happens with SimpleHistory. If I remove SimpleHistory, it works fine.

**Comment by Eisa01** [comment]
Can you provide me with the error log

**Comment by LampPrinter** [comment]
> Can you provide me with the error log


`Playing: /Users/xyz/My Files/Torrents/High.Tension.2003.DC.1080p.BluRay.x264-nikt0.mp4
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (ac3 6ch 48000Hz)
     Audio --aid=2 --alang=eng (ac3 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=eng (*) (mov_text)
File tags:
 Title: High.Tension.2003.DC.1080p.BluRay.x264-nikt0
[auto_profiles] Applying auto profile: Video
[auto_profiles] Applying auto profile: save-pos-for-long-videos
Track switched:
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (ac3 6ch 48000Hz)
     Audio --aid=2 --alang=eng (ac3 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=eng (*) (mov_text)
[select_eng_sub] setting sub 1
[autosub] Reactivate external subtitle files:
Track list:
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (ac3 6ch 48000Hz)
     Audio --aid=2 --alang=eng (ac3 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=eng (*) (mov_text)
[autosub] English embedded subtitles active
[autosub] => NOT downloading new subtitles
[SimpleHistory] Added the below into history
[SimpleHistory] High.Tension.2003.DC.1080p.BluRay.x264-nikt0.mp4  🕒  00:00:00.000
Using hardware decoding (videotoolbox).
AO: [coreaudio] 48000Hz stereo 2ch floatp
VO: [libmpv] 1920x1080 videotoolbox[nv12]
AV: 01:30:44 / 01:30:44 (100%) A-V:  0.000
[--------------------------------------------------------------------------------+]
[auto_profiles] Applying auto profile: exit-fullscreen-at-eof
AV: 01:30:44 / 01:30:44 (100%) A-V:  0.000
[--------------------------------------------------------------------------------+]
[SimpleHistory] Added the below into history
[SimpleHistory] High.Tension.2003.DC.1080p.BluRay.x264-nikt0.mp4  🕒  00:00:00.000

Assertion failed: (mpctx->stop_play), function play_current_file, file loadfile.c, line 1785.
zsh: abort      /Applications/mpv.app/Contents/MacOS/mpv`

**Comment by Eisa01** [comment]
It seems to be a limitation that a function (if it is heavy) couldn't be loaded fully when using on_unload hook. It is a tough one, I will see if there is a workaround.

**Comment by Eisa01** [comment]
Try the new version and let me know if it fixes it for you

**Comment by LampPrinter** [comment]
> Try the new version and let me know if it fixes it for you

Fixed 👍.
