### ISSUE TITLE
SimpleHistory: option to change startup behavior

### ISSUE THREAD

**Issue by Eisa01** [Eisa01/mpv-scripts#73]
Option to change startup behavior when mpv is idle, e.g.: resume play back with position and without position.
reference to #60 discussion.

**Comment by Eisa01** [comment]
@vitormathews
update to 1.1.5 both script and conf as it has new option for 
`startup_idle_behavior`
change `startup_idle_behavior=none` to `startup_idle_behavior=resume` for immediately resuming playback of last item when mpv launches.

Let me know if that solves it for you

**Comment by vitormathews** [comment]
> @vitormathews update to 1.1.5 both script and conf as it has new option for `startup_idle_behavior` change `startup_idle_behavior=none` to `startup_idle_behavior=resume` for immediately resuming playback of last item when mpv launches.
> 
> Let me know if that solves it for you

Yes, now it's working perfectly, thank you very much!
