### ISSUE TITLE
[SmartCopyPaste] Default xclip copy command issue with Dolphin File Manager

### ISSUE THREAD

**Issue by xfzv** [Eisa01/mpv-scripts#74]
When copying a file from Dolphin (KDE Plasma File Manager) and trying to paste it in mpv, I'm getting the following error:

```
File Doesn't Exist:
file:///path/to/the/file
```

This is because Dolphin adds `file://` before the file/directory path when copying (Ctrl+c). I guess it's used, among other things, to differentiate files and directories from text in the clipboard system tray applet:

![image](https://user-images.githubusercontent.com/78810647/211780527-837a2504-ef13-4cdf-8020-cdae06bf07a8.png)

A workaround is to use `Copy location` (Ctrl+Alt+c by default) instead of regular copy (Ctrl+c), but it's not as convenient:

![image](https://user-images.githubusercontent.com/78810647/211781057-d740d28a-ec00-4f9d-971f-d7ad4bead215.png)

I tried to use `linux_copy=xclip -selection clipboard -o | awk -F "file://" {'print $2'}` in `SmartCopyPaste.conf` but it doesn't seem to work (although it works in the shell).

Is there any way to ignore or accept `file://`?

**Comment by Eisa01** [comment]
I'll see what I can do about it

**Comment by Eisa01** [comment]
In the conf file where it says `paste_prot/ocols`, add `file:` and it should make it work. I have also updated the default config to include the changes.
paste_protocols=["https?://", "magnet:", "rtmp:", "file:"]
