### ISSUE TITLE
SimpleHistory - File path is not stored in log

### ISSUE THREAD

**Issue by falsified** [Eisa01/mpv-scripts#75]
Not sure if its by design, but the simplehistory stores all files played with no path. Resuming doesnt work unless you are opening mpv from the directory where the file exists.

Can paths be added to the mpvHistory.log as a delimited value, so that the history menu can show full path and file or just file?

Also, thank you for the awesome set of scripts!

**Comment by Eisa01** [comment]
That is strange, paths are stored in `mpvHistory.log` and there is an option to show full path and file or just file.
Appreciate if you can show me a sample of your `mpvHistory.log` file so I can investigate this.

**Comment by falsified** [comment]
[Wednesday/January 25/01/2023 16:33:16] [EMBER] Taishou Otome Otogibanashi - 01.mkv | length=1437.034 | time=0.751
[Wednesday/January 25/01/2023 16:33:20] [EMBER] Tsuki to Laika to Nosferatu - 01.mkv | length=1431.104 | time=2.628
[Wednesday/January 25/01/2023 16:33:21] [EMBER] Uramichi Oniisan - 11.mkv | length=1427.029 | time=0.584
[Wednesday/January 25/01/2023 17:16:31] pN0xG73tEF.mkv | length=4847.328 | time=0

#--Show file paths instead of media-title                                                                                                                                                            
show_paths=yes

I did try with yes and no, and it only produces the filename with no path

note: i am only using simplehistory, no bookmark, paste, etc

**Comment by Eisa01** [comment]
This is definitely a bug. 
Are you using the latest SimpleHistory 1.1.6, also revert to the default config of SimpleHistory.
Try using mpv with the default config and only use SimpleHistory 1.1.6 script with its default config (without any other script). This is to know whether another script or a specific configuration is conflicting.

If the issue still persists, provide me with the following, your mpv version, and OS details.

**Comment by falsified** [comment]
Just tried with no aother scripts, and freshly downloaded conf + latest simplehistory. with path yes/no, and its still producing no path

Arch 6.1.7
mpv 0.35.0

**Comment by Eisa01** [comment]
> Just tried with no aother scripts, and freshly downloaded conf + latest simplehistory. with path yes/no, and its still producing no path
> 
> Arch 6.1.7 mpv 0.35.0

Was your mpv.conf also set to default?
Appreciate if you can refer me to the download link of the arch linux you're using so I test it

**Comment by falsified** [comment]
Yes, tried with no mpv.conf (defaulted player settings)

arch is just archlinux.org

**Comment by Eisa01** [comment]
> 

Thanks. I'll be checking it

**Comment by Eisa01** [comment]
@falsified 
I am unable to reproduce your issue. I have installed Arch Linux with KDE and mpv 0.35.0 via pacman and flatpak.
Both generated the fullpath inside the log file without any issue.
Contact me on eisa_01@outlook.com to investigate this further.

**Comment by Eisa01** [comment]
Closed, unable to reproduce.
