### ISSUE TITLE
mpv --pause not working when using SimpleHistory

### ISSUE THREAD

**Issue by candrapersada** [Eisa01/mpv-scripts#76]
why `mpv --pause Files/URL`  not working when using SimpleHistory?

**Comment by Eisa01** [comment]
From my testing SimpleHistory doesn't interfere with `--pause` flag.
Perhaps a certain configuration or another script/s is causing this. 

Kindly verify and provide some logs / samples.

**Comment by candrapersada** [comment]
`mpv --pause https://www.youtube.com/watch?v=09cYQJBgKEs`

**Comment by Eisa01** [comment]
Just tested, pausing works fine.
Kindly test without any script and default mpv config. 
Then test with only SimpleHistory using default config.
