### ISSUE TITLE
Ignored "+" on the url

### ISSUE THREAD

**Issue by lacroix005** [Eisa01/mpv-scripts#80]
When pasting a URL for a video that contains a plus sign (+) to MPV, the link after plus sign will be ignored. This will cause the MPV to not recognize the video and crash.

For example: https://lewp.vizcloud.club/simple/EqPFIfsQWADtjDlGha7rC5Au+VwAuuO0AEJ7rqk+wYMnU94US2El_Po4w12g/br/H4/v.m3u8
Or any video on 9anime(dot)to with VidStream host.

When I paste that URL into MPV window, it will crash. However, when I run the MPV command with that link, it will open the video normally.
![image](https://user-images.githubusercontent.com/31035900/222940122-a278c027-3761-421a-8a02-83e24ffacd8d.png)

MPV : mpv 0.35.0-255-g16f0cd54
Script : SmartCopyPaste_II 3.1, SimpleHistory 1.1.5
OS : Windows 11

**Comment by Eisa01** [comment]
Thanks for letting me know, I will check it.

**Comment by Eisa01** [comment]
Should be fixed now, download the latest version of the script and let me know the results.
