### ISSUE TITLE
missing youtube next or Playlist in SimpleHistory and SimpleBookmark

### ISSUE THREAD

**Issue by candrapersada** [Eisa01/mpv-scripts#81]
why is youtube next or Playlist missing in SimpleHistory and SimpleBookmark?

**Comment by Eisa01** [comment]
I didn't understand, please provide me more information and screenshot of what you are getting and what is expected

**Comment by Eisa01** [comment]
That is because the history and bookmark saves the file but not the playlist. 

You cannot bookmark a playlist, you can only bookmark the file. 

Sadly, this is related to #77 which has been marked as limitations from mpv developers.
