### ISSUE TITLE
Any way to rename / tag bookmarks?

### ISSUE THREAD

**Issue by Azkaas** [Eisa01/mpv-scripts#87]
Hi
Ive tried to find a option that lets me rename the bookmark, but i cant seem to find it. It would be really helpful if we could search for specific bookmarks in our workflow.

**Comment by Eisa01** [comment]
You can add a bookmark to group, functions same as tagging. And you can define what each group name is.
Basically you press `ctrl+g` on a bookmark to add into group, press ctrl+g multiple times and you can cycle towards all defined groups in the config file.

You can read more about it here:
https://github.com/Eisa01/mpv-scripts/issues/62#issuecomment-1289274982

**Comment by Azkaas** [comment]
Thanks for the quick reply!

This is awesome, and gets 50% of what i want :) However it would still be really good if there is a way to actually rename the bookmark itself, since i like to make multiple bookmarks in a single video for different topics, which i can then easily search through with the LogManager.

**Comment by Azkaas** [comment]
Awesome :)

I will use this workaround for now. Would be great to have a feature where we could rename it directly from mpv, but i understand if it is too time consuming.

Thanks once again! Both for the reply, and a awesome script
