### ISSUE TITLE
Empty space in copied YouTube URL

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [Eisa01/mpv-scripts#97]
On copying a YouTube url, there's an empty space between the link and the timestamp query, e.g. `https://www.youtube.com/watch?v=UA40uWi6a1w &t=47.981314647981s`
Fwiw this doesn't happen with Twitch videos.

**Comment by Eisa01** [comment]
Provide script name + version,
Also mpv version

**Comment by limaceous-bushwhacker** [comment]
My bad, it's `SmartCopyPaste_II` Version: 3.2.1. mpv version is 0.34.1

**Comment by Eisa01** [comment]
I haven't had the time to check it, was it user config error?
